'use client';
// Five purpose-built practice interactions for the Copilot learning path.
import { useState } from 'react';
import { CheckCircle2, Play, ShieldCheck, Sparkles } from 'lucide-react';
function Shell({title,intro,children}:{title:string;intro:string;children:React.ReactNode}){return <section className="copilot-lab"><header><span><Sparkles/>INTERACTIVE COPILOT LAB</span><h3>{title}</h3><p>{intro}</p></header>{children}</section>}
const Result=({ok,text}:{ok:boolean;text:string})=><div className={`copilot-lab-result ${ok?'ok':'warn'}`} aria-live="polite">{ok?<CheckCircle2/>:<ShieldCheck/>}<p>{text}</p></div>;
export function CopilotSuggestionLab(){const [choice,setChoice]=useState('');return <Shell title="Inspect a suggestion before accepting it" intro="Check Copilot's late-fee calculation against the business rule."><pre><code>{`double fee = overdue * days * 0.02;`}</code></pre><p className="copilot-mission">Rule: 2% per day, capped at 15%.</p><div className="copilot-actions"><button onClick={()=>setChoice('accept')}>Accept as written</button><button onClick={()=>setChoice('edit')}>Add a 15% cap</button><button onClick={()=>setChoice('reject')}>Reject without review</button></div>{choice&&<Result ok={choice==='edit'} text={choice==='edit'?'Correct. Edit, test, then accept.':choice==='accept'?'Valid syntax, wrong business rule. Plausible is not verified.':'Inspect the suggestion and make the smallest safe correction.'}/>}</Shell>}
export function CopilotChatLab(){const [context,setContext]=useState<string[]>([]);const toggle=(v:string)=>setContext(s=>s.includes(v)?s.filter(x=>x!==v):[...s,v]);const good=['Failing test output','RefundService.java','Expected business rule'].every(x=>context.includes(x))&&!context.includes('Unrelated CSS file');return <Shell title="Assemble enough context for Copilot Chat" intro="Choose what Chat needs to diagnose a refund-test failure."><div className="copilot-context-grid">{['Failing test output','RefundService.java','Expected business rule','Unrelated CSS file'].map(x=><button className={context.includes(x)?'active':''} onClick={()=>toggle(x)} key={x}>{x}</button>)}</div><Result ok={good} text={good?'Strong context. Ask for an explanation before a fix.':'Choose failure evidence, relevant code and expected behaviour; unrelated files add noise.'}/></Shell>}
export function CopilotPromptLab(){const [level,setLevel]=useState(0);const prompts=['Fix this code','In RefundService.java, fix the duplicate-refund bug','In RefundService.java, prevent duplicate refunds without changing the public API. Preserve idempotency and add tests for repeated transaction IDs.'];return <Shell title="Turn a vague request into a testable prompt" intro="Add context, constraints and acceptance evidence."><blockquote>{prompts[level]}</blockquote><div className="copilot-actions"><button disabled={level===0} onClick={()=>setLevel(v=>v-1)}>Less context</button><button disabled={level===2} onClick={()=>setLevel(v=>v+1)}>Improve prompt</button></div><Result ok={level===2} text={level===2?'Scope, constraints and completion evidence are now clear.':level===1?'Better scope; add constraints and a success check.':'The request leaves the file, defect and expected result unclear.'}/></Shell>}
export function CopilotAgentLab(){const steps=['Read issue and repository rules','Propose a bounded plan','Edit the smallest file set','Run tests and inspect failures','Review diff before approval'];const [step,setStep]=useState(0);return <Shell title="Supervise a multi-file agent task" intro="Agent mode can act; the developer owns boundaries and approval."><ol className="copilot-agent-steps">{steps.map((x,i)=><li className={i===step?'active':i<step?'done':''} key={x}><button onClick={()=>setStep(i)}><span>{i<step?'✓':i+1}</span>{x}</button></li>)}</ol><button className="copilot-run" disabled={step===4} onClick={()=>setStep(v=>Math.min(4,v+1))}><Play/>Run next controlled step</button><Result ok={step===4} text={step===4?'Inspect the diff, evidence and security impact before approval.':'Keep planning, execution and validation visible.'}/></Shell>}
export function CopilotGovernanceLab(){const [risk,setRisk]=useState('');const data:{[k:string]:string}={docs:'Light review: accuracy, tone and repository standards.',api:'Standard review: tests, auth boundaries, error handling and diff inspection.',payment:'High-risk review: domain owner, security review, threat checks, audit evidence and staged release.'};return <Shell title="Match review depth to change impact" intro="Choose a change to calculate its governance gate."><div className="copilot-actions">{[['docs','README wording'],['api','Customer API'],['payment','Payment authorization']].map(([k,v])=><button className={risk===k?'active':''} onClick={()=>setRisk(k)} key={k}>{v}</button>)}</div>{risk?<Result ok={risk!=='payment'} text={data[risk]}/>:<p className="copilot-mission">Select a change.</p>}</Shell>}
