'use client';

import { useState } from 'react';
import { ArrowRight, BriefcaseBusiness, CheckCircle2, Code2, Compass, Gauge, Handshake, Network, Play, RefreshCcw, ShieldCheck, Sparkles, Target, Users } from 'lucide-react';

type Variant='role'|'skillset'|'lifecycle'|'trust'|'career';
const data={
 role:{title:'Is this really an FDE problem?',scenario:['A bank bought OrbitAI','Legacy systems block standard onboarding','An FDE embeds, integrates and proves production value'],flow:[['Customer reality','Observe workflow'],['Problem frame','Define outcome'],['Build','Integrate safely'],['Production','Measure adoption']],choices:[['Standard setup','Known configuration; no custom engineering',false],['FDE engagement','Ambiguous workflow + integration + production ownership',true],['Sales demo','Useful before purchase, not for delivery ownership',false]],result:'Use an FDE when customer reality must shape engineering delivery.'},
 skillset:{title:'Balance the three FDE skill pillars',scenario:['Rahul is a strong coder','He cannot explain value to a CFO','Technical depth must combine with commercial thinking and ambiguity handling'],flow:[['Technical','Build + debug'],['Commercial','Connect value'],['Communication','Align people'],['Ambiguity','Decide with evidence']],choices:[['Only coding','Deep engineering without stakeholder alignment',false],['Only consulting','Good framing without production implementation',false],['Balanced profile','Technical + commercial + field judgement',true]],result:'The strongest FDE is T-shaped, not merely the best algorithm solver.'},
 lifecycle:{title:'Choose the next engagement step',scenario:['QuickLogix asks for a six-week delivery','Karthik wants to code immediately','Divya begins with discovery and a measurable outcome'],flow:[['Discover','Users + systems'],['Define','Outcome + scope'],['Design','Thin slice'],['Deploy','Real workflow'],['Handoff','Adoption + learning']],choices:[['Start coding','Fast motion, weak evidence',false],['Run discovery','Expose constraints before architecture hardens',true],['Promise full scope','Creates delivery risk before unknowns are known',false]],result:'Discovery reduces rework by revealing constraints while change is still cheap.'},
 trust:{title:'Respond to a skeptical customer',scenario:['A previous vendor failed','The customer expects another black-box delivery','The FDE builds with the customer through visible evidence'],flow:[['Listen','Acknowledge history'],['Co-design','Agree success'],['Show work','Demo small increments'],['Prove','Share evidence'],['Transfer','Build ownership']],choices:[['Defend the product','Makes the conversation vendor-centred',false],['Build in isolation','Delays feedback until risk is high',false],['Co-create visibly','Turns progress into shared evidence',true]],result:'Trust grows through predictable behaviour, transparency and shared ownership.'},
 career:{title:'Plan an FDE transition',scenario:['A developer wants an FDE role','Job titles and compensation attract attention','A portfolio must prove field-facing delivery capability'],flow:[['Depth','Choose technical base'],['Breadth','Learn business context'],['Evidence','Build client-style project'],['Practice','Explain trade-offs'],['Target','Apply by role scope']],choices:[['Chase title only','No evidence of customer-to-production ownership',false],['Build an FDE portfolio','Show discovery, architecture, delivery and outcome',true],['Copy US salary figures','Ignores market, location and role scope',false]],result:'Career readiness is demonstrated through evidence, not title familiarity.'}
} as const;
const icons=[Compass,Target,Code2,Gauge,Handshake];

export function FDEScenarioExplorer({variant}:{variant:Variant}){const item=data[variant];const [active,setActive]=useState(0);const footer=<figcaption aria-live="polite"><CheckCircle2/><span>{item.scenario[active]}</span><button onClick={()=>setActive((active+1)%item.scenario.length)}>{active===item.scenario.length-1?'Replay':'Next'}<ArrowRight/></button></figcaption>;
if(variant==='role')return <figure className="fde-lab fde-role-bridge"><header><div><small>IMPLEMENTATION GAP FINDER</small><strong>{item.title}</strong></div><Compass/></header><div className="fde-bridge"><button className={active===0?'active':''} onClick={()=>setActive(0)}><small>PRODUCT BOUGHT</small><b>OrbitAI platform</b><span>{item.scenario[0]}</span></button><span className="fde-gap"><i>GAP</i><b>Legacy reality</b><button onClick={()=>setActive(1)}>Inspect blocker</button></span><button className={active===2?'active':''} onClick={()=>setActive(2)}><small>OUTCOME NEEDED</small><b>Production value</b><span>{item.scenario[2]}</span></button></div>{footer}</figure>;
if(variant==='skillset')return <figure className="fde-lab fde-skill-balance"><header><div><small>SKILL BALANCE BOARD</small><strong>{item.title}</strong></div><Gauge/></header><div className="fde-pillars">{['Technical depth','Business language','Field judgement'].map((label,i)=><button key={label} className={active===i?'active':''} onClick={()=>setActive(i)}><span><i style={{height:`${[92,38,72][i]}%`}}/></span><b>{label}</b><small>{item.scenario[i]}</small></button>)}</div>{footer}</figure>;
if(variant==='lifecycle')return <figure className="fde-lab fde-start-line"><header><div><small>START-LINE SIMULATOR</small><strong>{item.title}</strong></div><Network/></header><div className="fde-path-choice"><button className={active===1?'risk active':'risk'} onClick={()=>setActive(1)}><Play/><b>Code immediately</b><small>Unknown constraints stay hidden</small></button><span>OR</span><button className={active===2?'safe active':'safe'} onClick={()=>setActive(2)}><Compass/><b>Discover first</b><small>Map workflow and define evidence</small></button></div><div className="fde-path-result"><i className={active===2?'safe':''}/><span>{active===2?'Lower rework risk: build from evidence.':active===1?'Higher rework risk: architecture hardens too early.':item.scenario[0]}</span></div>{footer}</figure>;
if(variant==='trust')return <figure className="fde-lab fde-trust-dialogue"><header><div><small>CUSTOMER CONVERSATION</small><strong>{item.title}</strong></div><Handshake/></header><div className="fde-chat"><button className={active===0?'active customer':''} onClick={()=>setActive(0)}><small>CUSTOMER</small><span>“The previous vendor failed. Why should we trust this?”</span></button><button className={active===1?'active weak':''} onClick={()=>setActive(1)}><small>WEAK RESPONSE</small><span>“Our product is better. Let us build it first.”</span></button><button className={active===2?'active strong':''} onClick={()=>setActive(2)}><small>FDE RESPONSE</small><span>“Let us agree on one small win and build it together.”</span></button></div>{footer}</figure>;
return <figure className="fde-lab fde-career-steps"><header><div><small>CAREER EVIDENCE PATH</small><strong>{item.title}</strong></div><BriefcaseBusiness/></header><div className="fde-steps">{['Engineering base','Customer evidence','FDE-ready portfolio'].map((label,i)=><button key={label} className={active===i?'active':''} onClick={()=>setActive(i)} style={{transform:`translateY(${(2-i)*12}px)`}}><i>0{i+1}</i><b>{label}</b><small>{item.scenario[i]}</small></button>)}</div>{footer}</figure>}

export function FDEWorkflowExplorer({variant}:{variant:Variant}){const item=data[variant];const [active,setActive]=useState(0);return <figure className="fde-lab fde-workflow"><header><div><small>INTERACTIVE WORKFLOW · {active+1}/{item.flow.length}</small><strong>Follow the work—not just the job title</strong></div><Network/></header><div className="fde-progress"><i style={{width:`${((active+1)/item.flow.length)*100}%`}}/></div><div>{item.flow.map(([title,note],i)=>{const Icon=icons[i];return <span key={title}><button className={active===i?'active':''} aria-pressed={active===i} onClick={()=>setActive(i)}><Icon/><b>{title}</b><small>{note}</small></button>{i<item.flow.length-1&&<ArrowRight/>}</span>})}</div><figcaption><span><b>Stage {active+1}: {item.flow[active][0]}</b> — {item.flow[active][1]}</span><button onClick={()=>setActive((active+1)%item.flow.length)}>{active===item.flow.length-1?'Replay':'Continue'}<ArrowRight/></button></figcaption></figure>}

export function FDEConceptLab({variant}:{variant:Variant}){const item=data[variant];const [choice,setChoice]=useState<number|null>(null);const selected=choice===null?null:item.choices[choice];const score=selected?(selected[2]?100:35):0;return <section className="fde-concept-lab"><header><span><Sparkles/></span><div><small>DECISION SIMULATOR</small><h3>{item.title}</h3><p>Choose an action, inspect the consequence, then reset and compare.</p></div></header><div className="fde-choice-grid">{item.choices.map(([title,note,good],i)=><button className={choice===i?(good?'selected correct':'selected wrong'):''} aria-pressed={choice===i} onClick={()=>setChoice(i)} key={title}><span>{i+1}</span><b>{title}</b><small>{note}</small></button>)}</div><div className={`fde-decision-result ${selected?(selected[2]?'success':'warning'):''}`} aria-live="polite">{selected?(selected[2]?<CheckCircle2/>:<ShieldCheck/>):<Play/>}<div><small>DELIVERY CONFIDENCE · {score}%</small><span className="fde-meter"><i style={{width:`${score}%`}}/></span><b>{selected?(selected[2]?item.result:`Reconsider: ${selected[1]}`):'Select one option to reveal the outcome.'}</b></div>{selected&&<button onClick={()=>setChoice(null)}><RefreshCcw/>Reset</button>}</div></section>}

export function FDEOutcomeVisual({variant}:{variant:Variant}){const item=data[variant];return <figure className="fde-outcome"><header><BriefcaseBusiness/><div><small>VISIBLE OUTCOME</small><strong>What changes after good FDE work?</strong></div></header><div><span><Users/><b>Customer</b><small>Understands and owns the solution</small></span><ArrowRight/><span><Gauge/><b>Evidence</b><small>Production outcome is measurable</small></span><ArrowRight/><span><Sparkles/><b>Product</b><small>Reusable learning returns to the roadmap</small></span></div><figcaption>{item.result}</figcaption></figure>}
