'use client';

import { useMemo, useState } from 'react';
import { Bot, Braces, CheckCircle2, CircleAlert, Code2, Database, Gauge, Play, RefreshCw, Server, ShieldCheck, Sparkles, Wrench } from 'lucide-react';

function Shell({number,title,mission,progress,children}:{number:number;title:string;mission:string;progress:number;children:React.ReactNode}){return <section className={`java-lab java-lab-${number}`}><header><span><Code2/><small>JAVA APPLICATION LAB · BYTE 0{number}</small><strong>{title}</strong></span><em>BUILD · RUN · INSPECT</em></header><div className="java-mission"><span><small>ENGINEERING TASK</small><b>{mission}</b></span><i>{progress}%</i></div><div className="java-progress"><span style={{width:`${progress}%`}}/></div>{children}<footer><ShieldCheck/>Guided browser simulation · no credentials or external services required</footer></section>}
function Feedback({ok,title,children}:{ok:boolean;title:string;children:React.ReactNode}){return <div className={`java-feedback ${ok?'ok':'bad'}`}>{ok?<CheckCircle2/>:<CircleAlert/>}<span><b>{title}</b><p>{children}</p></span></div>}

export function JavaRequestLab(){
 const correct=['Controller','Service','AI Client','Response'];const options=['AI Client','Controller','Response','Service'];const [flow,setFlow]=useState<string[]>([]);const [run,setRun]=useState(false);const ok=flow.join('|')===correct.join('|');
 return <Shell number={1} title="Wire a Spring Boot AI request" mission="Arrange the layers so HTTP concerns, business logic and AI access stay separated." progress={run&&ok?100:Math.round(flow.length/4*70)}><div className="java-request"><code>POST /api/summarise</code><span>{`{"text":"Customer complaint…"}`}</span></div><div className="java-builder"><aside><small>AVAILABLE COMPONENTS</small>{options.map(x=><button disabled={flow.includes(x)} onClick={()=>{setFlow([...flow,x]);setRun(false)}} key={x}>{x}</button>)}</aside><main><small>YOUR REQUEST PATH</small>{flow.length?<ol>{flow.map((x,i)=><li key={x}><i>{i+1}</i><b>{x}</b><button onClick={()=>{setFlow(flow.filter(y=>y!==x));setRun(false)}}>×</button></li>)}</ol>:<p>Select the first application layer.</p>}</main></div><div className="java-actions"><button onClick={()=>{setFlow([]);setRun(false)}}><RefreshCw/>Reset</button><button className="java-run" disabled={flow.length<4} onClick={()=>setRun(true)}><Play/>Send request</button></div>{run&&<Feedback ok={ok} title={ok?'HTTP 200 · Clean layer boundary':'Request path is incorrectly coupled'}>{ok?'The controller accepts HTTP input, the service owns the use case, the AI client calls the model, and the response returns to the caller.':'Start at the controller. Keep business decisions in the service and external model access behind the AI client.'}</Feedback>}</Shell>
}

export function SpringAIClientLab(){
 const [system,setSystem]=useState(true);const [temperature,setTemperature]=useState(0.2);const [format,setFormat]=useState<'text'|'json'>('json');const [run,setRun]=useState(false);const reliable=system&&temperature<=0.4&&format==='json';
 const code=`chatClient.prompt()\n  ${system?'.system("Summarise support complaints factually")\n  ':''}.user(complaint)\n  .options(temperature(${temperature.toFixed(1)}))\n  .call()\n  .${format==='json'?'entity(ComplaintSummary.class)':'content()'};`;
 return <Shell number={2} title="Configure a predictable Spring AI call" mission="Choose prompt and output controls suitable for a support-summary API." progress={run&&reliable?100:60}><div className="java-control-grid"><button aria-pressed={system} onClick={()=>{setSystem(!system);setRun(false)}}>System instruction <b>{system?'ON':'OFF'}</b></button><label>Temperature <b>{temperature.toFixed(1)}</b><input type="range" min="0" max="1" step="0.1" value={temperature} onChange={e=>{setTemperature(Number(e.target.value));setRun(false)}}/></label><div><button aria-pressed={format==='text'} onClick={()=>{setFormat('text');setRun(false)}}>Text</button><button aria-pressed={format==='json'} onClick={()=>{setFormat('json');setRun(false)}}>Typed JSON</button></div></div><div className="java-code"><header><Braces/>ChatClient configuration</header><pre>{code}</pre></div><button className="java-run" onClick={()=>setRun(true)}><Play/>Run model call</button>{run&&<Feedback ok={reliable} title={reliable?'Validated structured response':'Response contract is fragile'}>{reliable?'Low temperature, a clear system instruction and typed output create a more testable API contract.':'For this business task, add a system instruction, prefer a low temperature and return a validated type instead of unstructured prose.'}</Feedback>}{run&&reliable&&<div className="java-output"><small>CODE RESULT</small><code>{`{"category":"refund","summary":"UPI reversal delayed","priority":"HIGH"}`}</code></div>}</Shell>
}

export function JavaRAGLab(){
 const chunks=[['refund','Refund Policy §2.1','Failed UPI payments reverse within 3–5 working days.'],['card','Card Guide §4','Disputes require transaction evidence.'],['kyc','KYC Guide §1','Identity documents must be current.']];const [selected,setSelected]=useState<string[]>([]);const [run,setRun]=useState(false);const ok=selected.length===1&&selected[0]==='refund';
 return <Shell number={3} title="Build the evidence context for Spring AI" mission="Select only the chunk that should reach QuestionAnswerAdvisor." progress={run&&ok?100:selected.length?55:15}><div className="java-question"><b>QUESTION</b>When will my failed UPI payment be reversed?</div><div className="java-chunks">{chunks.map(([id,title,text])=><button aria-pressed={selected.includes(id)} onClick={()=>{setSelected(selected.includes(id)?selected.filter(x=>x!==id):[...selected,id]);setRun(false)}} key={id}><Database/><span><b>{title}</b><small>{text}</small></span></button>)}</div><button className="java-run" disabled={!selected.length} onClick={()=>setRun(true)}><Play/>Run advisor chain</button>{run&&<Feedback ok={ok} title={ok?'Grounded context assembled':'Context contains noise or misses the answer'}>{ok?'The advisor can attach this policy passage before ChatClient generates the response.':'Use the smallest sufficient evidence set. Irrelevant chunks consume context and can distract generation.'}</Feedback>}{run&&ok&&<div className="java-trace"><span><Database/>VectorStore</span><i>→</i><span><Wrench/>Advisor</span><i>→</i><span><Bot/>ChatClient</span><i>→</i><span><CheckCircle2/>Cited answer</span></div>}</Shell>
}

export function JavaToolLab(){
 const [request,setRequest]=useState<'read'|'write'>('read');const [confirm,setConfirm]=useState(false);const [run,setRun]=useState(false);const allowed=request==='read'||confirm;
 const call=request==='read'?'getAccountBalance(customerId)':'closeAccount(customerId)';
 return <Shell number={4} title="Control Spring AI tool execution" mission="Decide when an @Tool method may run and when human approval is required." progress={run&&allowed?100:confirm?70:35}><div className="java-tool-choice"><button aria-pressed={request==='read'} onClick={()=>{setRequest('read');setConfirm(false);setRun(false)}}>Read balance</button><button aria-pressed={request==='write'} onClick={()=>{setRequest('write');setConfirm(false);setRun(false)}}>Close account</button></div><div className="java-tool-card"><header><Wrench/><span><small>MODEL REQUESTED TOOL</small><b>{call}</b></span></header><code>{`@Tool(description = "${request==='read'?'Read current balance':'Close a customer account'}")`}</code>{request==='write'&&<label><input type="checkbox" checked={confirm} onChange={e=>{setConfirm(e.target.checked);setRun(false)}}/>Human approval received</label>}</div><button className="java-run" onClick={()=>setRun(true)}><Play/>Evaluate and execute</button>{run&&<Feedback ok={allowed} title={allowed?'Tool policy passed':'High-impact action blocked'}>{allowed?'The tool receives validated arguments, executes with the user identity and records an audit event.':'Closing an account changes business state. Require explicit approval and least-privilege authorisation before execution.'}</Feedback>}</Shell>
}

export function JavaProductionLab(){
 const [timeout,setTimeoutValue]=useState(true);const [retry,setRetry]=useState(false);const [fallback,setFallback]=useState(true);const [metrics,setMetrics]=useState(true);const [run,setRun]=useState(false);const score=[timeout,retry,fallback,metrics].filter(Boolean).length;const safe=timeout&&fallback&&metrics;
 return <Shell number={5} title="Prepare an AI endpoint for failure" mission="Choose controls for an LLM provider that becomes slow and returns intermittent errors." progress={run&&safe?100:score*18}><div className="java-incident"><CircleAlert/><span><small>PRODUCTION INCIDENT</small><b>Latency: 9.2s · error rate: 12% · traffic rising</b></span></div><div className="java-guardrails">{[['Timeout',timeout,setTimeoutValue],['Limited retry',retry,setRetry],['Fallback response',fallback,setFallback],['Metrics and tracing',metrics,setMetrics]].map(([label,value,set])=><button aria-pressed={value as boolean} onClick={()=>{(set as (v:boolean)=>void)(!(value as boolean));setRun(false)}} key={label as string}><span>{value?'✓':'+'}</span>{label as string}</button>)}</div><button className="java-run" onClick={()=>setRun(true)}><Gauge/>Run incident simulation</button>{run&&<Feedback ok={safe} title={safe?'Service degrades safely':'Users remain exposed to provider failure'}>{safe?'The endpoint stops waiting, returns a controlled fallback and exposes telemetry for diagnosis. Retries must remain bounded to avoid amplifying overload.':'Add a timeout, controlled fallback and observability. Unlimited waiting or blind retries can exhaust application resources.'}</Feedback>}{run&&<div className="java-dashboard"><span>HTTP outcome<b>{safe?'200 FALLBACK':'5XX / TIMEOUT'}</b></span><span>Latency<b>{timeout?'2.0s capped':'9.2s'}</b></span><span>Trace<b>{metrics?'RECORDED':'MISSING'}</b></span></div>}</Shell>
}

export function JavaStoryVisual({variant}:{variant:'foundation'|'client'|'rag'|'tools'|'production'}){const data={foundation:['Request','Controller','Service','Response'],client:['Prompt','ChatClient','Model','Typed output'],rag:['Question','VectorStore','Advisor','Answer'],tools:['Intent','Policy','@Tool','Audit'],production:['Traffic','Guardrail','Fallback','Observe']}[variant];return <figure className={`java-story java-story-${variant}`}><figcaption><small>JAVA APPLICATION FLOW</small><strong>{data.join(' → ')}</strong></figcaption><div>{data.map((x,i)=><span key={x}><i>0{i+1}</i><b>{x}</b>{i<3&&<em>→</em>}</span>)}</div></figure>}
