'use client';

import { useState } from 'react';
import { ArrowRight, Bot, Braces, CheckCircle2, Code2, Database, FileSearch, FileText, Gauge, MessageSquareText, Play, RotateCcw, Search, ShieldCheck, Sparkles, TestTube2, Users, Wrench, XCircle } from 'lucide-react';

type Concept='foundation'|'model'|'chain'|'rag'|'memory'|'agent'|'production';

const sectionVisuals={
  foundation:{scenario:[['Need','Build a finance assistant'],['Problem','Every provider uses a different interface'],['Solution','LangChain gives the application a common model layer']],workflow:[['Messages','Keep system and user roles'],['Chat model','Generate the response'],['AIMessage','Return an object to Python']]},
  chain:{scenario:[['Need','Classify every expense'],['Problem','Manual prompt strings are hard to reuse'],['Solution','Template, model and parser become one chain']],workflow:[['Prompt','Insert the expense text'],['Model','Choose the category'],['Parser','Return a clean string']]},
  rag:{scenario:[['Need','Answer from a 40-page policy'],['Problem','Sending every page is slow and expensive'],['Solution','Retrieve only the relevant evidence']],workflow:[['Load + split','Prepare searchable chunks'],['Vector search','Find meaning-related passages'],['Grounded answer','Give evidence to the model']]},
  memory:{scenario:[['Need','Understand a follow-up question'],['Problem','“That” has no meaning without turn one'],['Solution','Load the correct session history']],workflow:[['Turn one','Save the first message'],['Session history','Load messages by ID'],['Turn two','Resolve the reference']]},
  agent:{scenario:[['Need','Read the current balance'],['Problem','The model cannot access live account data'],['Solution','Allow one validated read-only tool']],workflow:[['Decision','Select check_balance'],['Tool call','Run validated Python'],['Observation','Prepare the verified answer']]},
  model:{scenario:[['Need','Return predictable fields'],['Problem','Free text may break the application'],['Solution','Validate against a defined schema']],workflow:[['Message','Send the request'],['Model','Produce structured fields'],['Validation','Accept or reject']]},
  production:{scenario:[['Need','Release with confidence'],['Problem','One successful demo proves very little'],['Solution','Test quality, safety and recovery']],workflow:[['Evaluate','Run fixed cases'],['Protect','Check controls'],['Release','Monitor limited traffic']]},
} as const;

const results={
  invoke:{title:'AI MESSAGE RETURNED',output:'AIMessage(content="RAG finds relevant evidence before the model answers.")',why:'invoke sends role-based messages to the selected chat model. LangChain returns an AIMessage; your application still decides how to validate and use it.',steps:[[MessageSquareText,'Messages','System + user roles'],[Bot,'Chat model','Generates content'],[Braces,'AIMessage','Application receives object']]},
  chain:{title:'EXPENSE CATEGORY RETURNED',output:'Single input: Food\nBatch output: ["Travel", "Bills"]',why:'The template inserts each expense into the instruction. The model classifies it, and StrOutputParser converts the AIMessage into the plain string expected by the application.',steps:[[MessageSquareText,'Input value','Expense description'],[Braces,'Prompt template','Build instruction'],[Bot,'Model + parser','Return clean category']]},
  schema:{title:'TYPED TICKET RESULT',output:'category: access\nurgency: high\nreason: Payment succeeded but content remains locked',why:'The model response is parsed into the TicketResult schema. The allowed Literal values prevent an unexpected category from silently entering the workflow.',steps:[[MessageSquareText,'Ticket text','Unstructured input'],[Bot,'Structured model call','Classify fields'],[CheckCircle2,'TicketResult','Validated Python object']]},
  retrieve:{title:'RETRIEVED EVIDENCE',output:'1. leave-policy-v3.pdf · page 4 · score 0.91\n2. employee-faq.pdf · page 2 · score 0.78',why:'The query and stored chunks use the same embedding space. Similarity search returns candidate Documents with source metadata—not a final answer.',steps:[[Search,'Question vector','Meaning represented'],[Database,'Vector search','Nearest authorised chunks'],[FileText,'Documents','Text + source metadata']]},
  memory:{title:'FOLLOW-UP CONTEXT RESOLVED',output:'Turn 1: Food expense = Rs 4,500\nTurn 2: Swiggy portion = Rs 1,850',why:'RunnableWithMessageHistory loads messages for customer_12345 before the second call. The model can therefore resolve “that” as the food-expense total from the first turn.',steps:[[MessageSquareText,'Turn 1','Saved to session'],[Database,'Message history','Loaded by session ID'],[Bot,'Turn 2 answer','Reference resolved']]},
  agent:{title:'VERIFIED BALANCE ANSWER',output:'tool: check_balance\nargs: {"user_id":"PW12345"}\nobservation: Rs 24,500\nanswer: Your current balance is Rs 24,500.',why:'The model requests the read-only balance tool. Application code executes it with validated arguments, returns the observation, and the model converts that verified result into a user-facing answer.',steps:[[Bot,'Agent decision','Select check_balance'],[Wrench,'Read-only tool','Return live value'],[MessageSquareText,'Final answer','Use observation']]},
  tool:{title:'TOOL OBSERVATION',output:'tool: search_course_catalogue\nargs: {"topic":"Docker","level":"beginner"}\nresult: 3 published courses',why:'The model chooses a bounded tool. Application code validates the arguments, executes the function and returns the observation to the agent loop.',steps:[[Bot,'Agent decision','Select allowed tool'],[Wrench,'Tool execution','Validated arguments'],[MessageSquareText,'Observation','Evidence returns to model']]},
  trace:{title:'RELEASE EVIDENCE',output:'contract_tests: 28/28 PASS\ngrounded_answers: 93% PASS\np95_latency: 2.4s PASS\nprompt_injection: 20/20 PASS',why:'A production release needs separate evidence for code, AI quality, latency and safety. One successful model response cannot represent the whole system.',steps:[[TestTube2,'Evaluation set','Normal + difficult cases'],[Gauge,'Measured thresholds','Quality + latency + cost'],[ShieldCheck,'Release decision','Promote or block']]},
} as const;

type Outcome=keyof typeof results;

function Shell({number,title,intro,children}:{number:string;title:string;intro:string;children:React.ReactNode}){return <section className="lc-lab"><header><div><small>LANGCHAIN CONCEPT LAB {number}</small><h3>{title}</h3><p>{intro}</p></div><span className="lc-live"><i/> LIVE SIMULATOR</span></header><div className="lc-lab-rail" aria-hidden="true"><span>INPUT</span><b/><span>PROCESS</span><b/><span>OUTCOME</span></div>{children}<footer><Code2/><span><b>Safe practice environment</b> — no provider request or external action is executed.</span></footer></section>}

function FoundationLab(){const [layers,setLayers]=useState(['messages','model'] as string[]);const toggle=(x:string)=>setLayers(v=>v.includes(x)?v.filter(i=>i!==x):[...v,x]);return <Shell number="01" title="Build the application around the model" intro="Turn layers on and see what LangChain adds. The model creates language; the surrounding application owns contracts, evidence and actions."><div className="lc-foundation"><nav>{[['messages','Messages'],['model','Model'],['schema','Structured output'],['tools','Tools'],['tracing','Tracing']].map(([id,label])=><button key={id} aria-pressed={layers.includes(id)} className={layers.includes(id)?'active':''} onClick={()=>toggle(id)}>{layers.includes(id)?<CheckCircle2/>:<span/>}{label}</button>)}</nav><div className="lc-stack"><section><small>USER NEED</small><b>“Explain RAG simply”</b></section><ArrowRight/><section className={layers.includes('messages')?'on':''}><MessageSquareText/><b>Messages</b><small>Preserve roles</small></section><ArrowRight/><section className={layers.includes('model')?'core on':'core'}><Bot/><b>Model</b><small>Generates</small></section><ArrowRight/><section className={layers.includes('schema')?'on':''}><Braces/><b>Result contract</b><small>{layers.includes('schema')?'Typed output':'Free text'}</small></section></div><div className="lc-layer-summary" aria-live="polite"><span><Sparkles/></span><p><b>{layers.length} application layer{layers.length===1?'':'s'} active</b><small>{layers.includes('tools')?'The model may request an allowed tool. ':'No tool access. '}{layers.includes('tracing')?'Execution can be inspected.':'Add tracing when the workflow must be observed.'}</small></p></div></div></Shell>}

function ModelLab(){const [mode,setMode]=useState<'good'|'invalid'|'timeout'>('good');const [run,setRun]=useState(false);const data={good:['access','high','Accepted by TicketResult'],invalid:['payments','urgent','Rejected: values outside schema'],timeout:['—','—','Provider timeout → controlled failure']}[mode];return <Shell number="02" title="Classify one ticket and inspect the contract" intro="Run three provider outcomes. Notice that HTTP success, schema validity and business correctness are different checks."><nav className="lc-options">{[['good','Valid result'],['invalid','Invalid fields'],['timeout','Timeout']].map(([id,label])=><button className={mode===id?'active':''} onClick={()=>{setMode(id as typeof mode);setRun(false)}} key={id}>{label}</button>)}</nav><div className="lc-model-grid"><section><small>INPUT MESSAGE</small><MessageSquareText/><b>Payment succeeded, but the course is locked.</b><button onClick={()=>setRun(true)}><Play/>Invoke classifier</button></section><ArrowRight/><section><small>MODEL RESPONSE</small><Bot/><code>{run?`category: ${data[0]}\nurgency: ${data[1]}`:'Waiting for invoke()'}</code></section><ArrowRight/><section className={run?(mode==='good'?'pass':'fail'):''}><small>PYTHON DECISION</small>{run&&mode==='good'?<CheckCircle2/>:run?<XCircle/>:<ShieldCheck/>}<b>{run?data[2]:'Validate result'}</b></section></div></Shell>}

function ChainLab(){const [step,setStep]=useState(0);const stages=[['User value','"Swiggy ₹450"'],['Prompt template','Insert value into instruction'],['Chat model','Classify the expense'],['Typed result','category: food']];return <Shell number="02" title="Build one predictable prompt pipeline" intro="Run the value through one stage at a time. A chain is useful when the order is fixed and every output has a known next destination."><div className="lc-agent"><ol>{stages.map(([name],i)=><li className={i===step?'active':i<step?'done':''} key={name}><button onClick={()=>setStep(i)}><span>{i<step?<CheckCircle2/>:i+1}</span>{name}</button></li>)}</ol><section><small>PIPELINE STEP {step+1} OF 4</small><strong>{stages[step][0]}</strong><code>{stages[step][1]}</code><dl><div><dt>Order</dt><dd>fixed</dd></div><div><dt>Next step</dt><dd>{step===3?'complete':stages[step+1][0]}</dd></div><div><dt>Agent choice</dt><dd>not needed</dd></div></dl><button disabled={step===3} onClick={()=>setStep(v=>Math.min(3,v+1))}>Pass value forward <ArrowRight/></button></section></div></Shell>}

function RagLab(){const [k,setK]=useState(2);const [searched,setSearched]=useState(false);return <Shell number="03" title="Watch a question become retrieved evidence" intro="Choose how many chunks to retrieve, then inspect why source metadata must travel with every passage."><div className="lc-rag"><section><small>QUESTION</small><b>How many casual leave days are available?</b><label>Chunks to retrieve <input type="range" min="1" max="4" value={k} onChange={e=>{setK(Number(e.target.value));setSearched(false)}}/><strong>k = {k}</strong></label><button onClick={()=>setSearched(true)}><Search/>Run similarity search</button></section><div className="lc-rag-pipeline"><span><FileText/><b>Policy files</b><small>Load + split</small></span><ArrowRight/><span><Sparkles/><b>Embeddings</b><small>Represent meaning</small></span><ArrowRight/><span><Database/><b>Vector store</b><small>Search nearest chunks</small></span></div><section className={searched?'ready':''}><small>RETRIEVER OUTPUT</small>{searched?<>{Array.from({length:k},(_,i)=><article key={i}><FileSearch/><div><b>{i===0?'leave-policy-v3.pdf':'employee-faq.pdf'}</b><small>page {i+4} · score {(0.91-i*.11).toFixed(2)}</small></div></article>)}<p>These are candidates. The model has not answered yet.</p></>:<><Database/><b>Waiting for search</b></>}</section></div></Shell>}

function AgentLab(){const steps=[['Goal','Find a beginner Docker course'],['Decision','Call search_course_catalogue'],['Tool','3 published courses returned'],['Observation','Compare level and duration'],['Answer','Recommend one verified course']] as const;const [active,setActive]=useState(0);return <Shell number="05" title="Step through the model–tool–observation loop" intro="Move through the loop one state at a time. The agent may choose a tool, but code still owns validation, permissions and stopping limits."><div className="lc-agent"><ol>{steps.map(([name],i)=><li className={i===active?'active':i<active?'done':''} key={name}><button onClick={()=>setActive(i)}><span>{i<active?<CheckCircle2/>:i+1}</span>{name}</button></li>)}</ol><section aria-live="polite"><small>STEP {active+1} OF 5</small><div className="lc-progress"><i style={{width:`${(active+1)*20}%`}}/></div><strong>{steps[active][0]}</strong><code>{steps[active][1]}</code><dl><div><dt>Tool calls</dt><dd>{active>=2?'1':'0'}</dd></div><div><dt>Evidence</dt><dd>{active>=2?'available':'waiting'}</dd></div><div><dt>External change</dt><dd>none</dd></div></dl><button disabled={active===4} onClick={()=>setActive(v=>Math.min(4,v+1))}>Next state <ArrowRight/></button></section></div></Shell>}

function MemoryLab(){const [remember,setRemember]=useState(false);return <Shell number="04" title="See why a follow-up needs thread memory" intro="Compare the same second question with and without earlier messages. Memory is context supplied to the model—not a magical permanent brain."><div className="lc-model-grid"><section><small>TURN 1</small><MessageSquareText/><b>My transaction limit is ₹50,000.</b><button onClick={()=>setRemember(v=>!v)}>{remember?<RotateCcw/>:<Play/>}{remember?'Clear thread':'Save to thread'}</button></section><ArrowRight/><section><small>TURN 2</small><MessageSquareText/><b>Can I increase it?</b><code>{remember?'thread_id: customer-42':'no previous messages'}</code></section><ArrowRight/><section className={remember?'pass':'fail'}><small>MODEL CONTEXT</small>{remember?<CheckCircle2/>:<XCircle/>}<b>{remember?'“it” = transaction limit':'“it” is unknown'}</b></section></div></Shell>}

function ProductionLab(){const gates=['Contract tests','AI evaluation','Security controls','Rollback ready'];const [passed,setPassed]=useState<string[]>([]);const ready=passed.length===gates.length;return <Shell number="05" title="Release only when four kinds of evidence agree" intro="Run each gate independently. A healthy container is useful evidence, but it does not prove grounded answers, safe tools or recoverability."><div className="lc-release"><section><small>RELEASE CANDIDATE</small><b>course-assistant:2.0.0</b><p>Model, prompt, retriever and tool versions are pinned together.</p></section><div>{gates.map(g=><button className={passed.includes(g)?'pass':''} onClick={()=>setPassed(v=>v.includes(g)?v.filter(x=>x!==g):[...v,g])} key={g}>{passed.includes(g)?<CheckCircle2/>:<TestTube2/>}<span><b>{g}</b><small>{passed.includes(g)?'Evidence passed':'Run gate'}</small></span></button>)}</div><section className={ready?'ready':''}>{ready?<CheckCircle2/>:<ShieldCheck/>}<small>DEPLOYMENT</small><b>{ready?'Ready for controlled release':'Release blocked'}</b><p>{ready?'Start with limited traffic and monitor.':`${gates.length-passed.length} gate${gates.length-passed.length===1?'':'s'} missing.`}</p><button onClick={()=>setPassed([])} disabled={!passed.length}><RotateCcw/>Reset</button></section></div></Shell>}

export function LangChainConceptLab({concept}:{concept:Concept}){if(concept==='foundation')return <FoundationLab/>;if(concept==='model')return <ModelLab/>;if(concept==='chain')return <ChainLab/>;if(concept==='rag')return <RagLab/>;if(concept==='memory')return <MemoryLab/>;if(concept==='agent')return <AgentLab/>;return <ProductionLab/>}

export function LangChainScenarioVisual({concept}:{concept:Concept}){const [active,setActive]=useState(0);const item=sectionVisuals[concept];return <figure className="lc-section-visual lc-scenario-visual"><header><small>SCENARIO MAP</small><strong>See why this concept is needed</strong><span>Choose a stage</span></header><div className="lc-scenario-steps">{item.scenario.map(([label,text],i)=><button key={label} className={active===i?'active':''} onClick={()=>setActive(i)} aria-pressed={active===i}><i>0{i+1}</i><span><small>{label}</small><b>{text}</b></span>{i<2&&<ArrowRight/>}</button>)}</div><figcaption aria-live="polite"><Sparkles/><span><small>CURRENT UNDERSTANDING</small><b>{item.scenario[active][1]}</b></span></figcaption></figure>}

export function LangChainWorkflowExplorer({concept}:{concept:Concept}){const [active,setActive]=useState(0);const item=sectionVisuals[concept];return <figure className="lc-section-visual lc-workflow-explorer"><header><small>INTERACTIVE WORKFLOW</small><strong>Follow the data one step at a time</strong><span>Step {active+1} of 3</span></header><div className="lc-workflow-track">{item.workflow.map(([label,text],i)=><button key={label} className={active===i?'active':i<active?'done':''} onClick={()=>setActive(i)}><i>{i<active?<CheckCircle2/>:i+1}</i><span><b>{label}</b><small>{text}</small></span>{i<2&&<ArrowRight/>}</button>)}</div><footer><button disabled={active===2} onClick={()=>setActive(v=>Math.min(2,v+1))}>Show next step <ArrowRight/></button><p aria-live="polite"><b>{item.workflow[active][0]}:</b> {item.workflow[active][1]}</p></footer></figure>}

export function LangChainCodeOutcome({variant}:{variant:Outcome}){const item=results[variant];const [active,setActive]=useState(0);return <figure className="lc-outcome"><header><div><small>CODE RESULT</small><strong>{item.title}</strong></div><span><Play/> CLICK EACH EXECUTION STEP</span></header><div className="lc-outcome-body"><section><small>EXPECTED OUTPUT</small><pre><code>{item.output}</code></pre></section><aside aria-live="polite"><small>WHY THIS OUTPUT?</small><p>{item.why}</p><b className="lc-active-explanation">Step {active+1}: {item.steps[active][1]} — {item.steps[active][2]}</b></aside></div><div className="lc-outcome-flow"><div><small>VISUAL EXECUTION</small><b>Choose a stage to inspect it</b></div>{item.steps.map(([Icon,title,note],i)=><button className={active===i?'active':''} onClick={()=>setActive(i)} key={title}><span><Icon/></span><b>{title}</b><small>{note}</small>{i<item.steps.length-1&&<ArrowRight/>}</button>)}</div></figure>}
