'use client';
/* eslint-disable react/no-unescaped-entities */

import { useState } from 'react';
import type { CSSProperties } from 'react';
import { ArrowDown, ArrowRight, Braces, CheckCircle2, Code2, Eye, FileJson, Gauge, KeyRound, MessageSquareText, Play, RotateCcw, SearchCheck, ShieldCheck, Sparkles, TestTube2, Users, Wrench, XCircle } from 'lucide-react';

type Concept = 'foundations'|'api'|'genai'|'agents'|'production';

function LabShell({number,title,intro,children}:{number:string;title:string;intro:string;children:React.ReactNode}) {return <section className="python-code-lab"><header><div><small>PYTHON LEARNING LAB {number}</small><h3>{title}</h3><p>{intro}</p></div><span><Code2/> CODE → BEHAVIOUR → OUTPUT</span></header>{children}<footer><Eye/>Interactive learning model — it does not execute code or change an external system.</footer></section>}

function FoundationsLab(){const [genre,setGenre]=useState('Animation');const [rating,setRating]=useState('U');const [ran,setRan]=useState(false);const eligible=genre==='Animation'&&rating==='U';return <LabShell number="01" title="See how input travels through a Python function" intro="Change the inputs, read the highlighted decision, then run the function to connect each code line to the returned value."><div className="python-foundation-board"><section className="python-input-panel"><small>1 · INPUT VALUES</small><label>Genre<select value={genre} onChange={e=>{setGenre(e.target.value);setRan(false)}}><option>Animation</option><option>Drama</option></select></label><label>Age rating<select value={rating} onChange={e=>{setRating(e.target.value);setRan(false)}}><option>U</option><option>UA</option></select></label><div className="python-memory-view"><b>Python memory</b><code>genre → {genre}</code><code>rating → {rating}</code></div></section><section className="python-code-window"><header><i/><i/><i/><span>recommender.py</span></header><pre><code><em>1</em> def recommend_movie(genre, rating):{`\n`}<em>2</em>   <mark>if rating == "U" and</mark>{`\n`}<em>3</em>      <mark>genre == "Animation":</mark>{`\n`}<em>4</em>     return "Family Animation"{`\n`}<em>5</em>   return "Explore other titles"</code></pre><button type="button" onClick={()=>setRan(true)}><Play/>Run function</button></section><section className={`python-output-panel ${ran?'ready':''}`}><small>3 · RETURNED OUTPUT</small>{ran?<><span>{eligible?<CheckCircle2/>:<SearchCheck/>}</span><strong>{eligible?'Family Animation':'Explore other titles'}</strong><p>{eligible?'Both conditions are True, so Python runs line 4.':'At least one condition is False, so Python reaches line 5.'}</p></>:<><span><Code2/></span><strong>Waiting to run</strong><p>The function returns one value; it does not print every internal step.</p></>}</section></div><div className="python-explain-strip"><b>What just happened?</b><span>Inputs entered memory</span><ArrowRight/><span><code>if</code> produced True or False</span><ArrowRight/><span><code>return</code> sent one result back</span></div></LabShell>}

function ApiLab(){const [scenario,setScenario]=useState<'valid'|'rate'|'broken'>('valid');const [sent,setSent]=useState(false);const data={valid:{status:'200 OK',body:'{"id":"mv-101","runtime_minutes":88}',verdict:'Accepted: required fields and values are valid',ok:true},rate:{status:'429 Too Many Requests',body:'{"retry_after":2}',verdict:'Wait, then retry with a maximum attempt count',ok:false},broken:{status:'200 OK',body:'{"name":"Family Night"}',verdict:'Rejected: id and runtime_minutes are missing',ok:false}}[scenario];return <LabShell number="02" title="Inspect a real request, response and validation decision" intro="Choose a provider response. The HTTP status and JSON body answer different questions, so Python checks both."><nav className="python-lab-options">{[['valid','Valid response'],['rate','Rate limit'],['broken','Broken JSON']].map(([id,label])=><button key={id} className={scenario===id?'active':''} onClick={()=>{setScenario(id as typeof scenario);setSent(false)}}>{label}</button>)}</nav><div className="python-api-board"><section><small>PYTHON REQUEST</small><pre><code>requests.get({`\n`}  "/v1/titles",{`\n`}  params={`{`}"language": "Tamil"{`}`},{`\n`}  timeout=10{`\n`})</code></pre><button onClick={()=>setSent(true)}><Play/>Send simulated request</button></section><ArrowRight/><section className={sent?'active':''}><small>PROVIDER RESPONSE</small><b>{sent?data.status:'Not sent'}</b><pre><code>{sent?data.body:'Response will appear here'}</code></pre></section><ArrowRight/><section className={sent?(data.ok?'valid':'invalid'):''}><small>PYTHON DECISION</small>{sent?(data.ok?<CheckCircle2/>:<XCircle/>):<ShieldCheck/>}<b>{sent?data.verdict:'Status check + JSON validation'}</b><p>{sent&&scenario==='broken'?'HTTP succeeded, but the application contract failed.':'Transport and data validation stay separate.'}</p></section></div></LabShell>}

function GenAiLab(){const [candidate,setCandidate]=useState<'verified'|'invented'>('verified');const [checked,setChecked]=useState(false);const valid=candidate==='verified';return <LabShell number="03" title="Separate the model proposal from the application decision" intro="The LLM may write a confident answer. Python compares its title ID and constraints with approved catalogue evidence before the user sees it."><div className="python-context-ribbon"><span><Users/><b>Viewer need</b>Tamil · U rating · ≤ 90 min</span><ArrowRight/><span><SearchCheck/><b>Approved catalogue</b>mv-101 · 88 min · Tamil · U</span></div><div className="python-genai-board"><section><small>LLM PROPOSAL</small><nav>{[['verified','mv-101'],['invented','mv-999']].map(([id,label])=><button className={candidate===id?'active':''} onClick={()=>{setCandidate(id as typeof candidate);setChecked(false)}} key={id}>{label}</button>)}</nav><pre><code>{`{`}{`\n`}  "title_id": "{candidate==='verified'?'mv-101':'mv-999'}",{`\n`}  "confidence": 0.94{`\n`}{`}`}</code></pre></section><section className="python-validation-code"><small>DETERMINISTIC PYTHON CHECK</small><pre><code>if title_id not in catalogue:{`\n`}  reject("Unknown title"){`\n`}elif runtime &gt; 90:{`\n`}  reject("Too long"){`\n`}else:{`\n`}  approve()</code></pre><button onClick={()=>setChecked(true)}><ShieldCheck/>Validate proposal</button></section><section className={checked?(valid?'approved':'rejected'):''}><small>USER-FACING RESULT</small>{checked?(valid?<CheckCircle2/>:<XCircle/>):<Sparkles/>}<strong>{!checked?'Waiting for Python':valid?'Grounded recommendation':'Recommendation blocked'}</strong><p>{!checked?'Model confidence is not proof.':valid?'ID, language, rating and runtime match approved facts.':'mv-999 is absent from the approved catalogue.'}</p></section></div></LabShell>}

function AgentLab(){const steps=[['Goal','Prepare a weekend watchlist','No external action'],['Tool call','search_titles(language="Tamil")','Read-only operation'],['Observation','3 verified titles returned','State updated with evidence'],['Proposal','Add mv-101 to shared watchlist','Approval required'],['Confirmation','write tool returned success','Now completion may be claimed']] as const;const [active,setActive]=useState(0);return <LabShell number="04" title="Step through an agent loop and watch state change" intro="An agent does not jump from goal to success. Move one step at a time and notice where evidence, approval and confirmation enter the loop."><div className="python-agent-layout"><ol>{steps.map(([name],i)=><li className={i===active?'active':i<active?'done':''} key={name}><button onClick={()=>setActive(i)}><span>{i<active?<CheckCircle2/>:i+1}</span>{name}</button></li>)}</ol><section><small>CURRENT STEP {active+1} OF 5</small><strong>{steps[active][0]}</strong><code>{steps[active][1]}</code><p>{steps[active][2]}</p><div className="python-agent-state"><b>Agent state</b><span>goal: weekend watchlist</span><span>evidence: {active>=2?'3 titles':'waiting'}</span><span>approval: {active>=4?'approved':active===3?'required':'not requested'}</span><span>external change: {active===4?'confirmed':'not completed'}</span></div><button disabled={active===4} onClick={()=>setActive(v=>Math.min(v+1,4))}>{active===3?'Approve and run tool':'Next step'}<ArrowRight/></button></section></div></LabShell>}

function ProductionLab(){const gates=[['Tests','42 passed'],['AI evaluation','91% grounded'],['Security','0 critical issues'],['Rollback','v1.3.2 ready']] as const;const [passed,setPassed]=useState<number[]>([]);const all=passed.length===gates.length;return <LabShell number="05" title="Build release evidence instead of trusting one green signal" intro="Run each independent gate. Deployment stays blocked until code, AI quality, security and recovery evidence are all present."><div className="python-release-board"><section><small>RELEASE CANDIDATE</small><strong>movie-assistant:1.4.0</strong><p>A running container proves only that the process started.</p></section><div>{gates.map(([name,result],i)=><button className={passed.includes(i)?'passed':''} key={name} onClick={()=>setPassed(p=>p.includes(i)?p.filter(x=>x!==i):[...p,i])}><span>{passed.includes(i)?<CheckCircle2/>:<TestTube2/>}</span><b>{name}</b><small>{passed.includes(i)?result:'Run check'}</small></button>)}</div><section className={all?'ready':''}>{all?<CheckCircle2/>:<ShieldCheck/>}<small>DEPLOYMENT DECISION</small><strong>{all?'Ready for controlled release':'Release blocked'}</strong><p>{all?'Start with limited traffic and monitor quality, latency and cost.':`${gates.length-passed.length} evidence gate${gates.length-passed.length===1?'':'s'} still missing.`}</p><button disabled={!passed.length} onClick={()=>setPassed([])}><RotateCcw/>Reset evidence</button></section></div></LabShell>}

export function PythonConceptLab({concept}:{concept:Concept}) {if(concept==='foundations')return <FoundationsLab/>;if(concept==='api')return <ApiLab/>;if(concept==='genai')return <GenAiLab/>;if(concept==='agents')return <AgentLab/>;return <ProductionLab/>}

const stories = {
  foundations:[[Code2,'Recommendation rule','Logic is repeated in three UI handlers.','Move the rule into one typed function.','Every screen uses the same tested decision.'],[Braces,'Viewer profile','Preferences are stored in unrelated variables.','Group named fields in one dictionary.','The function receives one understandable profile.'],[Eye,'Invalid age','Text such as “twelve” crashes conversion.','Catch the expected ValueError.','The user sees a useful correction message.']],
  api:[[KeyRound,'Catalogue request','The API key is pasted into source code.','Load it from the runtime environment.','The repository contains no credential.'],[Gauge,'Slow provider','A request waits forever during an outage.','Add a timeout and bounded retry policy.','The app recovers or fails clearly.'],[FileJson,'Changed response','The provider removes a required field.','Validate the parsed JSON contract.','Bad data stops before reaching the UI.']],
  genai:[[SearchCheck,'Family recommendation','A model suggests a title unavailable in India.','Ground it with the current regional catalogue.','Python displays only a verified title.'],[ShieldCheck,'Age suitability','A fluent answer ignores the requested rating.','Validate rating and duration deterministically.','Unsafe or unsuitable output is rejected.'],[MessageSquareText,'Missing preference','The viewer gives no language or genre.','Return missing_information instead of guessing.','The interface asks one useful follow-up.']],
  agents:[[Wrench,'Title search','The model invents availability from memory.','Call a read-only catalogue tool.','The next step uses current tool evidence.'],[Users,'Shared watchlist','The agent is ready to change a family profile.','Pause with a precise approval proposal.','Nothing changes until a person approves.'],[Eye,'Repeated failure','The same tool times out repeatedly.','Stop at the retry and step limit.','The user receives an honest failure state.']],
  production:[[TestTube2,'Model update','A newer model changes recommendation quality.','Run the fixed evaluation set before release.','The team compares evidence, not impressions.'],[Gauge,'Cost spike','Long histories increase tokens silently.','Track tokens, latency and cost per request.','An alert catches abnormal usage.'],[RotateCcw,'Bad release','Version 1.4 fails its quality threshold.','Restore the compatible image, prompt and config.','Service returns to the known 1.3.2 state.']],
} as const;

export function PythonRealWorldVisual({variant}:{variant:keyof typeof stories}) {return <figure className="docker-market-visual docker-story-visual python-story-visual"><header><small>BEFORE → ENGINEERING ACTION → VISIBLE RESULT</small><strong>Follow the problem until the team can prove the result.</strong></header><div>{stories[variant].map(([Icon,title,before,action,after],index)=><article key={title} style={{'--market-delay':`${index*.7}s`} as CSSProperties}><span><Icon/></span><b>{title}</b><dl><div><dt>Before</dt><dd>{before}</dd></div><ArrowDown/><div><dt>Engineering action</dt><dd>{action}</dd></div><ArrowDown/><div><dt>Evidence after</dt><dd>{after}</dd></div></dl><i><CheckCircle2/> RESULT VERIFIED</i></article>)}</div><figcaption>These scenarios describe observable application behaviour—not private claims about any company’s internal systems.</figcaption></figure>}

const roles={
  foundations:[[Code2,'Python developer','Turn requirements into readable functions'],[TestTube2,'QA engineer','Test normal, empty and invalid inputs'],[Sparkles,'AI application developer','Connect rules to model workflows'],[Eye,'Code reviewer','Verify AI-generated code and dependencies']],
  api:[[Code2,'Backend developer','Build resilient API clients'],[ShieldCheck,'Security engineer','Protect credentials and private payloads'],[Gauge,'SRE engineer','Control timeouts, retries and limits'],[TestTube2,'QA engineer','Simulate provider failures and schema changes']],
  genai:[[Sparkles,'GenAI engineer','Assemble grounded prompts and structured output'],[Code2,'Backend developer','Own validation and business rules'],[ShieldCheck,'Responsible AI reviewer','Define abstention and human review'],[Gauge,'AI operations engineer','Track quality, latency and token cost']],
  agents:[[Sparkles,'Agent engineer','Design the decision loop and tool contracts'],[Code2,'Tool developer','Implement narrow authorised operations'],[ShieldCheck,'Security engineer','Separate read, write and approval permissions'],[Gauge,'Platform engineer','Trace steps, failures and execution evidence']],
  production:[[TestTube2,'AI evaluation engineer','Maintain regression and safety datasets'],[ShieldCheck,'Security engineer','Review identity, input and tool boundaries'],[Gauge,'SRE / AI operations','Monitor reliability, quality and cost'],[Code2,'Release engineer','Package, deploy and roll back known versions']],
} as const;

export function PythonRoleVisual({variant}:{variant:keyof typeof roles}) {return <figure className="docker-role-map python-role-map"><header><small>WHO USES THIS — AND WHAT DO THEY OWN?</small><strong>Connect each concept to an engineering responsibility.</strong></header><div>{roles[variant].map(([Icon,role,action],index)=><article key={role} style={{'--role-delay':`${index*.16}s`} as CSSProperties}><span><Icon/></span><div><b>{role}</b><p>{action}</p><small>Clear ownership</small></div><ArrowRight/></article>)}</div><figcaption><Sparkles/> One Python AI application is a team system: code, quality, security and operations work together.</figcaption></figure>}
