import { ArrowRight, BadgeCheck, Box, Braces, CheckCircle2, Code2, Container, Database, FileJson, FolderTree, Gauge, LogIn, KeyRound, MessageSquareText, Network, Play, RotateCcw, ShieldCheck, Sparkles, TestTube2, Users, Wrench } from 'lucide-react';
const outcomes={
  values:{label:'VALUES NOW IN MEMORY',output:'profile["language"] → "Tamil"\npreferred_genres[0] → "Animation"\n"SQL" in seen_title_ids → False',explain:'Each variable points to a value. The chosen data structure controls how the program reads and updates it.',steps:[[LogIn,'Literal values','Text · number · Boolean'],[Braces,'Python objects','List · dictionary · set'],[Database,'Memory','Names point to objects']]},
  function:{label:'RETURNED VALUE',output:'{"eligible": True,\n "reason": "Matches family rating and available time"}',explain:'Python checks the condition. Because both comparisons are True, the first return sends a dictionary back to the caller.',steps:[[LogIn,'Arguments','profile + 88 minutes'],[Code2,'if decision','True AND True'],[BadgeCheck,'return','Eligible result']]},
  error:{label:'VISIBLE USER OUTPUT',output:'Enter a whole number, such as 90',explain:'The invalid conversion raises ValueError. The matching except block catches that expected failure and returns a useful message.',steps:[[LogIn,'User types','ninety'],[Wrench,'int() conversion','Raises ValueError'],[MessageSquareText,'except block','Clear correction']]},
  request:{label:'SIMULATED RESPONSE',output:'HTTP 200 OK\n[{"id":"mv-101","language":"Tamil","rating":"U"}]',explain:'The timeout protects the waiting worker. raise_for_status checks HTTP failure before response.json converts the body into Python data.',steps:[[Code2,'Python client','GET + filters'],[Network,'HTTP service','Wait ≤ 10 seconds'],[FileJson,'Parsed JSON','Python list']]},
  validation:{label:'VALIDATION RESULT',output:'Accepted: mv-101\nRejected: Missing fields: ["runtime_minutes"]',explain:'Parsing answers “is this JSON?” Validation answers “does this data satisfy our application contract?”',steps:[[FileJson,'Parsed object','External data'],[ShieldCheck,'Required checks','Fields + values'],[BadgeCheck,'Decision','Accept or reject']]},
  secret:{label:'SAFE RUNTIME RESULT',output:'CATALOGUE_API_KEY loaded\nValue hidden from output and logs',explain:'The process receives the key from its environment. Source code contains only the variable name, never the credential value.',steps:[[KeyRound,'Secret store','Protected value'],[Container,'Runtime environment','Inject when starting'],[Code2,'Python process','Read by name']]},
  retry:{label:'RECOVERY AFTER A TEMPORARY FAILURE',output:'Attempt 1 → HTTP 429\nWait 2 seconds\nAttempt 2 → HTTP 200\nResult → 1 verified title',explain:'The client retries only a temporary rate-limit response. The attempt limit prevents an endless loop and the delay gives the provider time to recover.',steps:[[Network,'First call','429 rate limited'],[RotateCcw,'Bounded retry','Wait + try once more'],[BadgeCheck,'Recovered','Validated response']]},
  schema:{label:'VALIDATED MODEL OBJECT',output:'MovieRecommendation(\n  title_id="mv-101",\n  confidence=0.86,\n  missing_information=[]\n)',explain:'The response is now a typed object. Python must still verify that mv-101 exists in the approved catalogue.',steps:[[Sparkles,'LLM JSON','Proposed fields'],[Braces,'Pydantic','Shape + range checks'],[ShieldCheck,'Business validation','Catalogue truth']]},
  prompt:{label:'MODEL BOUNDARY',output:'Allowed: recommend IDs in AVAILABLE_TITLES\nAbstain: when required viewer data is missing',explain:'The instruction narrows model behaviour, while verified context supplies facts. Application code still enforces the final decision.',steps:[[MessageSquareText,'System rule','Role + limits'],[Database,'Approved context','Current facts'],[Sparkles,'Model proposal','Not final truth']]},
  grounded:{label:'VERIFIED RECOMMENDATION',output:'title_id: mv-101\nstatus: accepted\nreason: Tamil · U · 88 minutes\nshown_to_user: Yes',explain:'The model proposes mv-101. Python finds the same ID in the approved catalogue and independently verifies language, rating and runtime before displaying it.',steps:[[Sparkles,'Model proposal','mv-101'],[ShieldCheck,'Python checks','ID + constraints'],[BadgeCheck,'User result','Verified and shown']]},
  tools:{label:'TOOL CONTRACTS CREATED',output:'search_titles → read-only catalogue access\nadd_to_watchlist → approval token required',explain:'Two narrow tools expose different capabilities. Their permissions and evidence can be tested separately.',steps:[[Code2,'Python function','Bounded operation'],[Braces,'Typed contract','Inputs + result'],[ShieldCheck,'Permission','Read or write scope']]},
  approval:{label:'AGENT STATE',output:'status: approval_required\nexternal_change: not_completed\nnext_step: wait_for_human',explain:'The proposal is ready, but no write tool has run. The agent must not report the watchlist as updated.',steps:[[Sparkles,'Agent proposal','Planned change'],[Users,'Human review','Approve or reject'],[Wrench,'Write tool','Run only after approval']]},
  agentloop:{label:'CONFIRMED TOOL RESULT',output:'step 1 → 3 titles found\nstep 2 → mv-101 selected\nstep 3 → approval received\nstep 4 → watchlist_updated: true',explain:'The loop stops only after the authorised write tool returns success. A plan or approval alone is not completion evidence.',steps:[[Wrench,'Read tool','Collect evidence'],[Users,'Approval gate','Authorise exact change'],[CheckCircle2,'Write result','Completion confirmed']]},
  structure:{label:'RESPONSIBILITY MAP',output:'api → HTTP contract\nservices → workflow\nai → model and agent loop\ntools → bounded operations',explain:'Folders make ownership visible. Provider-specific AI code can change without mixing it into every business rule.',steps:[[FolderTree,'Clear modules','One responsibility'],[TestTube2,'Focused tests','Replace dependencies'],[ShieldCheck,'Safer change','Smaller blast radius']]},
  test:{label:'TEST OUTPUT',output:'test_rejects_title_over_time_limit PASSED\n1 passed',explain:'The assertion proves one deterministic rule for one named case. Other boundaries still need integration tests and AI evaluations.',steps:[[LogIn,'Known case','125 vs 90 minutes'],[Code2,'Function call','Returns False'],[CheckCircle2,'Assertion','Expected = actual']]},
  docker:{label:'CONTAINER RESULT',output:'Process started as user 10001\nApplication module: app\nSecrets expected at runtime',explain:'The image packages code and dependencies. It does not prove AI quality, permissions, monitoring or scalability.',steps:[[Box,'Docker image','Code + dependencies'],[Container,'Running process','Non-root user'],[ShieldCheck,'Runtime controls','Secrets + limits']]},
  evaluation:{label:'RELEASE DECISION',output:'grounded_accuracy: 94%  PASS\nsafe_stop_rate: 100%    PASS\nprompt_injection: 20/20 PASS\nrelease: APPROVED',explain:'Each test case is scored against a named criterion. The release passes because every required metric meets its threshold—not because one answer looked good.',steps:[[TestTube2,'Fixed cases','Normal + risky inputs'],[Gauge,'Score thresholds','Quality + safety'],[BadgeCheck,'Release gate','Evidence meets target']]},
} as const;

type Variant=keyof typeof outcomes;

export function PythonCodeOutcome({variant}:{variant:Variant}){const item=outcomes[variant];return <figure className="python-code-outcome"><header><div><small>CODE RESULT</small><strong>{item.label}</strong></div><span><Play/> TRACE THE EXECUTION</span></header><div className="python-code-output"><div><small>EXPECTED OUTPUT</small><pre><code>{item.output}</code></pre></div><aside><small>WHY THIS OUTPUT?</small><p><CheckCircle2/>{item.explain}</p></aside></div><div className="python-code-flow"><div className="python-code-flow-title"><small>VISUAL EXECUTION</small><b>Follow the value through the program</b></div>{item.steps.map(([Icon,label,note],index)=><div className="python-code-flow-wrap" key={label}><section><span><Icon/></span><b>{label}</b><small>{note}</small></section>{index<item.steps.length-1&&<ArrowRight/>}</div>)}</div></figure>}
