'use client';

import { useMemo, useState } from 'react';
import { CheckCircle2, CircleAlert, FileSearch, Gauge, LockKeyhole, Play, RefreshCw, Search, ShieldCheck, Trophy } from 'lucide-react';

function LabShell({number,title,mission,progress,children}:{number:number;title:string;mission:string;progress:number;children:React.ReactNode}){
  return <section className={`rag-lab rag-lab-${number}`}><header><span><FileSearch/><small>RAG SKILL LAB · BYTE 0{number}</small><strong>{title}</strong></span><em>LEARN BY DECIDING</em></header><div className="rag-mission"><span><small>YOUR MISSION</small><b>{mission}</b></span><i>{progress}% complete</i></div><div className="rag-progress"><span style={{width:`${progress}%`}}/></div>{children}<footer><ShieldCheck/>Safe guided environment · choices include immediate reasoning feedback</footer></section>;
}
function Feedback({correct,title,children}:{correct:boolean;title:string;children:React.ReactNode}){return <div className={`rag-feedback ${correct?'correct':'retry'}`}>{correct?<CheckCircle2/>:<CircleAlert/>}<span><b>{title}</b><p>{children}</p></span></div>}
function Complete(){return <div className="rag-complete"><Trophy/><span><small>SKILL UNLOCKED</small><b>Mission completed</b></span></div>}

const policies=[
  {id:'upi',title:'Failed UPI Refund Policy',preview:'Failed UPI payments are automatically reversed within 3–5 working days.',score:94},
  {id:'card',title:'Card Dispute Guide',preview:'Card disputes may take up to 30 days after evidence is received.',score:66},
  {id:'closure',title:'Account Closure Policy',preview:'Customers must clear pending balances before closure.',score:31},
];

export function RAGGroundingLab(){
  const [selected,setSelected]=useState('');const [checked,setChecked]=useState(false);const [compared,setCompared]=useState(false);const correct=selected==='upi';const progress=compared?100:checked&&correct?70:selected?35:10;
  return <LabShell number={1} title="Ground an answer with the right evidence" mission="Choose the passage that truly supports the customer’s refund question." progress={progress}><div className="rag-question"><b>CUSTOMER QUESTION</b><span>When will my failed UPI payment be refunded?</span></div><div className="rag-evidence-grid">{policies.map(p=><button aria-pressed={selected===p.id} onClick={()=>{setSelected(p.id);setChecked(false);setCompared(false)}} key={p.id}><span><Search/><b>{p.title}</b><small>Similarity {p.score}%</small></span><p>{p.preview}</p></button>)}</div><button className="rag-run" disabled={!selected} onClick={()=>setChecked(true)}><Play/>Use selected evidence</button>{checked&&<Feedback correct={correct} title={correct?'Correct evidence selected':'Related is not the same as relevant'}>{correct?'The passage directly answers both the payment type and refund timeline.':'This passage shares financial words, but it does not answer the failed UPI question. Select the policy with matching intent.'}</Feedback>}{checked&&correct&&<div className="rag-compare"><article><small>WITHOUT EVIDENCE</small><p>“Refunds usually take a few days.”</p><em>Vague · no source</em></article><article><small>WITH RAG EVIDENCE</small><p>“Your failed UPI payment should be reversed within 3–5 working days.”</p><em>Source: Refund Policy §2.1</em></article><button onClick={()=>setCompared(true)}>I can explain the difference</button></div>}{compared&&<Complete/>}</LabShell>;
}

export function RAGPipelineLab(){
  const correct=['Question','Retrieve','Augment','Generate'];const [chosen,setChosen]=useState<string[]>([]);const [checked,setChecked]=useState(false);const options=['Generate','Question','Augment','Retrieve'];const success=chosen.join('|')===correct.join('|');const add=(x:string)=>{if(!chosen.includes(x)){setChosen([...chosen,x]);setChecked(false)}};
  return <LabShell number={2} title="Build the RAG pipeline in the correct order" mission="Arrange the four stages before running the customer question." progress={success&&checked?100:Math.round(chosen.length/4*70)}><div className="rag-builder"><div><small>AVAILABLE STAGES</small>{options.map(x=><button disabled={chosen.includes(x)} onClick={()=>add(x)} key={x}>{x}</button>)}</div><div><small>YOUR PIPELINE</small><ol>{chosen.map((x,i)=><li key={x}><i>{i+1}</i><b>{x}</b><button aria-label={`Remove ${x}`} onClick={()=>{setChosen(chosen.filter(y=>y!==x));setChecked(false)}}>×</button></li>)}</ol>{!chosen.length&&<p>Select stages from the left.</p>}</div></div><div className="rag-actions"><button onClick={()=>{setChosen([]);setChecked(false)}}><RefreshCw/>Reset</button><button className="rag-run" disabled={chosen.length<4} onClick={()=>setChecked(true)}><Play/>Run pipeline</button></div>{checked&&<Feedback correct={success} title={success?'Pipeline executed successfully':'The sequence breaks the evidence flow'}>{success?'Question → Retrieve → Augment → Generate keeps evidence available before the model writes.':'The model must receive the question, retrieve evidence and add that evidence to context before generation.'}</Feedback>}{checked&&success&&<div className="rag-trace">{correct.map((x,i)=><span key={x}><i>0{i+1}</i><b>{x}</b><small>{['Failed UPI refund?','Refund Policy §2.1','Evidence attached','Cited 3–5 day answer'][i]}</small></span>)}</div>}</LabShell>;
}

export function RAGFailureLab(){
  const cases={stale:{signal:'Answer says 7 days. Current approved policy says 3–5 days, but the index still contains last year’s PDF.',answer:'stale',fix:'Remove the superseded file, re-index the approved version and add a freshness owner.'},chunk:{signal:'The retrieved passage contains the refund rule, but the exception starts in the next chunk and was not returned.',answer:'chunk',fix:'Re-chunk around the complete rule and exception, then rerun retrieval tests.'},retrieve:{signal:'The correct policy is indexed, but Card Dispute Guide ranked above Failed UPI Refund Policy.',answer:'retrieve',fix:'Tune hybrid search, metadata filters or reranking using benchmark questions.'}} as const;
  const [caseId,setCaseId]=useState<keyof typeof cases>('stale');const [choice,setChoice]=useState('');const [checked,setChecked]=useState(false);const current=cases[caseId];const success=choice===current.answer;
  return <LabShell number={3} title="Diagnose a failed RAG answer" mission="Read the evidence trace, identify the root cause, then choose the corrective action." progress={checked&&success?100:choice?55:20}><div className="rag-case-picker">{(Object.keys(cases) as (keyof typeof cases)[]).map((x,i)=><button aria-pressed={caseId===x} onClick={()=>{setCaseId(x);setChoice('');setChecked(false)}} key={x}>Incident {i+1}</button>)}</div><div className="rag-diagnosis"><Search/><span><small>EVIDENCE TRACE</small><b>What failed?</b><p>{current.signal}</p></span></div><div className="rag-choice-grid">{[['stale','Source freshness'],['chunk','Chunk boundary'],['retrieve','Retrieval ranking'],['model','Model size']].map(([id,label])=><button aria-pressed={choice===id} onClick={()=>{setChoice(id);setChecked(false)}} key={id}>{label}</button>)}</div><button className="rag-run" disabled={!choice} onClick={()=>setChecked(true)}><Play/>Submit diagnosis</button>{checked&&<Feedback correct={success} title={success?'Root cause identified':'Look upstream before blaming the model'}>{success?current.fix:'Use the trace: find the earliest stage where the expected evidence became wrong, incomplete or missing.'}</Feedback>}</LabShell>;
}

export function RAGEvaluationLab(){
  const [retrieval,setRetrieval]=useState(3);const [grounded,setGrounded]=useState(3);const [relevance,setRelevance]=useState(3);const [submitted,setSubmitted]=useState(false);const expected={retrieval:5,grounded:5,relevance:4};const delta=Math.abs(retrieval-5)+Math.abs(grounded-5)+Math.abs(relevance-4);const success=delta<=1;
  return <LabShell number={4} title="Act as the RAG quality reviewer" mission="Score one answer against its question and evidence, then compare with the expert review." progress={submitted?100:45}><div className="rag-eval-sample"><section><small>QUESTION</small><p>When will a failed UPI payment be reversed?</p></section><section><small>RETRIEVED EVIDENCE</small><p>Failed UPI payments are reversed within 3–5 working days.</p></section><section><small>MODEL ANSWER</small><p>Your payment will be reversed within 3–5 working days. Contact support if it is still pending after that.</p></section></div><div className="rag-meters"><Metric label="Retrieval relevance" help="Did search find evidence that answers the question?" value={retrieval} set={n=>{setRetrieval(n);setSubmitted(false)}}/><Metric label="Groundedness" help="Are the answer’s claims supported by the evidence?" value={grounded} set={n=>{setGrounded(n);setSubmitted(false)}}/><Metric label="Answer relevance" help="Does the response directly help the user?" value={relevance} set={n=>{setRelevance(n);setSubmitted(false)}}/></div><button className="rag-run" onClick={()=>setSubmitted(true)}><Gauge/>Compare with expert review</button>{submitted&&<Feedback correct={success} title={success?'Your review matches the evidence':'Recheck the unsupported instruction'}>Expert review: retrieval 5/5, groundedness 5/5, relevance 4/5. The timeline is supported; “contact support” is useful but not stated in the evidence.</Feedback>}{submitted&&<div className="rag-score-card"><span>YOUR SCORES<b>{retrieval} · {grounded} · {relevance}</b></span><span>EXPERT SCORES<b>{expected.retrieval} · {expected.grounded} · {expected.relevance}</b></span></div>}</LabShell>;
}

export function RAGProductionLab(){
  const [role,setRole]=useState<'customer'|'support'|'admin'>('customer');const [selected,setSelected]=useState<string[]>([]);const [ran,setRan]=useState(false);const sources=['Public FAQ','Own transactions','Other customer case','Support playbook','Audit logs'];const allowed=useMemo(()=>({customer:['Public FAQ','Own transactions'],support:['Public FAQ','Own transactions','Support playbook'],admin:['Public FAQ','Support playbook','Audit logs']})[role],[role]);const safe=selected.length>0&&selected.every(x=>allowed.includes(x));
  const toggle=(x:string)=>{setSelected(selected.includes(x)?selected.filter(y=>y!==x):[...selected,x]);setRan(false)};
  return <LabShell number={5} title="Enforce retrieval permissions before search" mission="Select only the knowledge sources this user role may retrieve." progress={ran&&safe?100:selected.length?55:15}><div className="rag-role-row">{(['customer','support','admin'] as const).map(x=><button aria-pressed={role===x} onClick={()=>{setRole(x);setSelected([]);setRan(false)}} key={x}><LockKeyhole/>{x[0].toUpperCase()+x.slice(1)}</button>)}</div><div className="rag-source-select"><small>SELECT RETRIEVAL SOURCES FOR: <b>{role}</b></small>{sources.map(x=><button aria-pressed={selected.includes(x)} onClick={()=>toggle(x)} key={x}><span>{selected.includes(x)?'✓':'+'}</span>{x}</button>)}</div><button className="rag-run" disabled={!selected.length} onClick={()=>setRan(true)}><Play/>Run permission check</button>{ran&&<Feedback correct={safe} title={safe?'Least-privilege retrieval passed':'Access violation blocked'}>{safe?`The retriever can search: ${selected.join(', ')}. The role and permitted source IDs will be logged.`:`${selected.filter(x=>!allowed.includes(x)).join(', ')} is not permitted for this role. Filter access before vector search—not after generation.`}</Feedback>}{ran&&safe&&<Complete/>}</LabShell>;
}

function Metric({label,help,value,set}:{label:string;help:string;value:number;set:(n:number)=>void}){return <label><span><b>{label}</b><em>{value}/5</em></span><small>{help}</small><input type="range" min="1" max="5" value={value} onChange={e=>set(Number(e.target.value))}/></label>}

export function RAGStoryVisual({variant}:{variant:'foundation'|'pipeline'|'failure'|'evaluation'|'production'}){
  const items={foundation:['Question','Retrieve','Evidence','Answer'],pipeline:['Load','Chunk','Embed','Search'],failure:['Source','Chunk','Rank','Generate'],evaluation:['Test set','Retrieve','Score','Improve'],production:['Identity','Filter','Answer','Audit']}[variant];
  return <figure className={`rag-story rag-story-${variant}`}><figcaption><small>VISUAL MODEL</small><strong>{items.join(' → ')}</strong></figcaption><div>{items.map((x,i)=><span key={x}><i>0{i+1}</i><b>{x}</b>{i<3&&<em>→</em>}</span>)}</div></figure>;
}
