import Link from 'next/link';
import { ArrowRight, ArrowUpRight, Mail, MessageCircleMore, Phone, Play } from 'lucide-react';
import { SocialIcon, socialLinks } from './SocialLinks';

const main = 'https://www.maanavan.com';
const membership = 'https://aiupskills.maanavan.com/memberships/6a20ef646786ea4efcafb247';
const playStoreUrl = 'https://play.google.com/store/apps/details?id=com.maanavanlearncode.courses&hl=en_IN';
const whatsappUrl = 'https://api.whatsapp.com/send?phone=%2B918073044127&text=Hi%2C%20I%E2%80%99m%20interested%20in%20your%20courses.%20Can%20you%20share%20more%20details%3F';

export function Footer() {
  return <footer className="site-footer maanavan-site-footer">
    <div className="footer-main maanavan-footer-main">
      <div className="footer-brand-column"><p className="site-footer-brand">MaanavaN<sup>®</sup></p><p className="site-footer-signature">AI UPSKILLS</p><p className="site-footer-copy">Practical AI and technology learning for Tamil-speaking learners worldwide, colleges, institutions and organisations.</p><a className="footer-membership-link" href={membership}>Explore All-Access Membership <ArrowRight/></a><div className="footer-contact"><a href="tel:+918073044127"><Phone/>+91 8073044127</a><a href="mailto:info@maanavan.com"><Mail/>info@maanavan.com</a></div><div className="footer-socials" aria-label="Follow MaanavaN">{socialLinks.map((social)=><a className={`social-brand social-${social.label.toLowerCase()}`} key={social.label} href={social.href} target="_blank" rel="noreferrer" aria-label={`Follow MaanavaN on ${social.label}`} title={social.label}><SocialIcon label={social.label}/></a>)}</div></div>
      <div className="footer-link-column"><h3>Courses</h3><a href={`${main}/course-library#categories`}>All Tamil Courses</a><a href={`${main}/free-courses`}>Free Courses for Students</a><a href={`${main}/solutions/career-learning-paths`}>Career Learning Paths</a><a href={`${main}/practice-tests`}>Practice Tests</a><a href={membership}>All-Access Membership</a></div>
      <div className="footer-link-column"><h3>Explore Bytes</h3><Link href="/handbooks/">All Handbooks</Link><Link href="/langchain/">LangChain Handbook</Link><Link href="/software-engineering/">GitHub Copilot Handbook</Link><Link href="/forward-deployed-engineer/">FDE Handbook</Link><Link href="/cloud-devops/">Docker Handbook</Link><Link href="/#bytes-library">Bytes Library</Link></div>
      <div className="footer-link-column"><h3>For Institutions</h3><a href={`${main}/solutions/ai-centre-of-excellence`}>AI Centre of Excellence</a><a href={`${main}/solutions/campus-skilling`}>Campus Skilling Programs</a><a href={`${main}/solutions/internship-programs`}>Internship Programs</a><a href={`${main}/solutions/placement-readiness`}>Placement Readiness</a><a href={`${main}/solutions/faculty-development`}>Faculty Development</a></div>
      <div className="footer-app-column"><h3>Learn on the go</h3><p>Continue your Tamil AI and technology learning anytime with the MaanavaN Upskills Android app.</p><a className="google-play-badge" href={playStoreUrl} target="_blank" rel="noreferrer" aria-label="Get MaanavaN Upskills on Google Play"><span className="google-play-icon"><Play/></span><span><small>GET IT ON</small><strong>Google Play</strong></span><ArrowUpRight className="google-play-arrow"/></a><a className="footer-platform-link" href="https://courses.maanavanlearncode.com/learn">Open Learning Platform <ArrowUpRight/></a><div className="footer-tamil-identity"><span>OUR TAMIL LEARNING IDENTITY</span><img src="/maanavan-tamil-logo.webp" alt="மாணவன் — MaanavaN Tamil logo"/></div></div>
    </div>
    <div className="footer-seo-directory"><div className="footer-seo-inner"><section><h3>Visual Technology Handbooks</h3><div><Link href="/langchain/">LangChain for GenAI and AI Agents Handbook</Link><Link href="/software-engineering/">GitHub Copilot Handbook</Link><Link href="/cloud-devops/">Docker Handbook</Link><Link href="/forward-deployed-engineer/">Forward Deployed Engineer Handbook</Link></div></section><section><h3>Continue with MaanavaN</h3><div><a href={`${main}/course-library`}>AI Courses in Tamil</a><a href={`${main}/insights`}>AI Learning Guides</a><a href={`${main}/solutions/career-learning-paths`}>Career Learning Paths</a><a href={`${main}/about/sathish-kumar`}>Meet Sathish Kumar</a></div></section><p className="footer-service-areas"><strong>Tamil-first learning worldwide:</strong> India · Sri Lanka · Singapore · Malaysia · UAE · UK · Europe · USA · Canada · Australia</p></div></div>
    <div className="footer-bottom maanavan-footer-bottom"><p>© 2026 MaanavaN®. All rights reserved.</p><p>MaanavaN® is a registered trademark. Other trademarks belong to their respective owners.</p><div><a href={`${main}/contact`}>Contact</a><a href="mailto:info@maanavan.com">Support</a></div></div>
    <a className="floating-whatsapp" href={whatsappUrl} target="_blank" rel="noreferrer" aria-label="Chat with MaanavaN on WhatsApp" title="Chat with us on WhatsApp"><span className="floating-whatsapp-ring" aria-hidden="true"/><MessageCircleMore/></a>
  </footer>;
}
