import Link from 'next/link';
import { ArrowRight, Box, Code2, FileSearch, Network, Workflow } from 'lucide-react';
import type { ByteMetadata } from '@/lib/types';

type PublishedHandbook = { slug:string; title:string; label:string; description:string; chapters:ByteMetadata[] };

export function PublishedHandbooks({handbooks}:{handbooks:PublishedHandbook[]}) {
  return <section className="published-handbooks"><div className="container-custom"><header className="published-heading"><div><p className="eyebrow dark">PUBLISHED HANDBOOKS</p><h2>Choose a path. Learn one connected chapter at a time.</h2><p>Each handbook connects visual explanations, real scenarios and practical engineering decisions.</p></div><Link href="/handbooks/">View handbook library <ArrowRight/></Link></header><div className="published-handbook-grid">{handbooks.map((handbook)=>{const isDocker=handbook.slug==='cloud-devops';const isLangChain=handbook.slug==='langchain';const isRag=handbook.slug==='rag-application-engineering';const Icon=handbook.slug==='software-engineering'?Code2:isDocker?Box:isLangChain?Network:isRag?FileSearch:Workflow;const tone=handbook.slug==='software-engineering'?'copilot':isDocker?'docker':isLangChain?'langchain':isRag?'rag':'fde';return <article className={`published-handbook-card published-${tone}`} key={handbook.slug}><div className="published-card-intro"><span className="published-card-icon"><Icon/></span><small>{handbook.label}</small><h3>{handbook.title}</h3><p>{handbook.description}</p><div className="handbook-card-focus"><b>VISUAL LEARNING PATH</b><span>Concept → workflow → application</span></div><Link className="handbook-card-cta" href={`/${handbook.slug}/`}>Explore handbook <ArrowRight/></Link></div><nav aria-label={`${handbook.title} chapters`}>{handbook.chapters.map((chapter,chapterIndex)=><Link href={`/${chapter.category}/${chapter.slug}/`} key={chapter.slug}><span>{String(chapterIndex+1).padStart(2,'0')}</span><div><small>BYTE {chapterIndex+1}</small><strong>{chapter.title}</strong></div><span className="chapter-link-icon" aria-hidden="true"><ArrowRight/></span></Link>)}</nav></article>})}</div></div></section>;
}
