import { ArrowRight, Lightbulb, MapPin } from 'lucide-react';

type Analogy = { title: string; scenario: string; steps: [string,string,string,string]; takeaway: string };

const analogies: Record<string, Analogy> = {
  '01-what-happens-when-you-send-whatsapp-message': { title:'A parcel with a delivery receipt', scenario:'You hand a parcel to a courier. They accept it, carry it to the recipient, and report delivery. If nobody is home, it waits for another attempt.', steps:['Hand over','Route','Wait or deliver','Confirm'], takeaway:'Sent, delivered and read describe different events in a message journey.' },
  '02-what-happens-when-you-complete-upi-payment': { title:'A transfer between two bank counters', scenario:'A transfer request passes through a shared exchange. Your bank checks and debits your account; the other bank credits the recipient. A receipt is useful only after the outcome is confirmed.', steps:['Request','Route','Debit','Confirm'], takeaway:'A pending screen means you should verify the final transaction state before retrying.' },
  '03-how-live-food-delivery-tracking-works': { title:'Following a bus on a map', scenario:'The bus reports its position from time to time. Your map updates when a fresh position arrives; between reports, the dot may move smoothly even though the bus has not sent a new point.', steps:['Locate','Send update','Show dot','Refresh'], takeaway:'A smooth map animation is not the same thing as a fresh GPS report.' },
  '04-how-netflix-adaptive-streaming-works': { title:'Keeping a small stack of pages ready', scenario:'Imagine reading while a helper brings the next few pages. If the helper slows down, shorter pages keep the reading going; if they speed up, higher quality pages can arrive.', steps:['Prepare','Fetch','Buffer','Adjust'], takeaway:'The player trades picture quality for continuous playback when the connection changes.' },
  '05-how-google-maps-routing-and-rerouting-works': { title:'Choosing streets as traffic changes', scenario:'A driver compares several streets by expected travel time. When a new delay appears, the driver checks whether another path is actually faster before turning.', steps:['Destination','Compare','Watch traffic','Reroute'], takeaway:'A route uses estimated travel time, and new conditions can change that estimate.' },
  '01-what-is-an-ai-agent-from-answering-to-taking-action': { title:'A travel desk that can complete the next step', scenario:'At a Chennai travel desk, answering the bus timing is different from checking seats, comparing options and preparing a booking for your approval.', steps:['Ask','Plan','Use service','Confirm'], takeaway:'An agent moves from giving information to pursuing a bounded outcome.' },
  '02-how-an-ai-agent-works-goal-reasoning-tools-actions': { title:'Finding the right bus connection', scenario:'A traveller going from Mayiladuthurai to Bengaluru checks the destination, compares routes, uses a timetable and changes the plan when a connection is unavailable.', steps:['Destination','Choose route','Check timetable','Replan'], takeaway:'An agent observes each result before choosing its next action.' },
  '03-tools-knowledge-memory-explained-simply': { title:'Choose the first shop task carefully', scenario:'A shop owner tests order-status replies before automating payments because the task repeats often, uses known data and has a safer review path.', steps:['Repetition','Time','Risk','Pilot'], takeaway:'Start with measurable work where mistakes can be caught safely.' },
  '04-build-first-ai-agent-without-coding': { title:'A new driver needs a seatbelt and rules', scenario:'Skill alone is not enough. Speed limits, supervision and a record of the journey reduce the impact of mistakes.', steps:['Limit','Validate','Approve','Record'], takeaway:'Useful autonomy needs technical controls around the model.' },
  '05-use-ai-agents-safely-responsibly': { title:'Learn in the shallow end first', scenario:'A swimmer builds confidence in a controlled area before moving deeper. An agent pilot should prove one safe workflow before expanding.', steps:['Identify','Try','Pilot','Review'], takeaway:'Scale from evidence, not excitement.' },
  '01-what-is-docker-containers-explained': { title:'A sealed meal box travels consistently', scenario:'A restaurant packs the dish, ingredients and handling instructions together so the same meal reaches Chennai or Coimbatore in a predictable form.', steps:['Recipe','Pack','Transport','Serve'], takeaway:'A container packages an application so it runs consistently across environments.' },
  '02-dockerize-first-python-application': { title:'Turning a kitchen recipe into a repeatable meal', scenario:'A written recipe lists ingredients and steps; the kitchen prepares a sealed meal box; the customer checks that it opens and tastes right.', steps:['App files','Dockerfile','Build image','Run + check'], takeaway:'The Dockerfile is the recipe; the image is the prepared package.' },
  '03-docker-ports-volumes-environment-variables': { title:'A shop needs an entrance, storeroom and settings', scenario:'Customers enter through a numbered door, stock remains in a storeroom after closing, and the price board changes without rebuilding the shop.', steps:['Port','Volume','Environment','Container'], takeaway:'Ports expose traffic, volumes preserve data and environment variables configure runtime.' },
  '04-multi-container-applications-docker-compose': { title:'A restaurant works through specialised counters', scenario:'Order desk, kitchen, billing and inventory perform different jobs but use one operating plan and communicate by known names.', steps:['Compose plan','Services','Network','Shared state'], takeaway:'Compose coordinates multiple specialised containers as one application.' },
  '05-dockerize-deploy-generative-ai-application': { title:'The parcel stays the same across delivery hubs', scenario:'A sealed package moves from the local hub to the city hub without being repacked; confidential delivery credentials are provided only at each authorised hub.', steps:['Build once','Store image','Add secrets','Run in cloud'], takeaway:'Deploy the same tested image and inject secrets only at runtime.' },
  '01-what-is-fastapi-turn-python-into-web-api': { title:'A restaurant menu exposes kitchen capabilities', scenario:'Customers do not enter the kitchen. They choose a named item, place a structured order and receive a predictable response at the counter.', steps:['Request','Endpoint','Python work','Response'], takeaway:'An API safely exposes selected application capabilities through clear contracts.' },
  '02-rest-api-validation-error-handling': { title:'A railway form is checked before booking', scenario:'The counter checks journey date, passenger details and required fields before attempting a reservation, then explains what must be corrected.', steps:['Input','Validate','Process','Clear result'], takeaway:'Validation rejects unusable requests before business logic runs.' },
  '03-databases-external-services-configuration': { title:'A service centre separates front desk and records', scenario:'The front desk accepts the request, a specialist applies the rule, the records room stores it and an external office is contacted only when necessary.', steps:['Route','Service','Database','External API'], takeaway:'Clear layers keep integrations replaceable and failures easier to locate.' },
  '04-build-stream-generative-ai-api': { title:'Live cricket commentary arrives before the final scorecard', scenario:'Listeners receive useful updates while the match continues, but the official scorecard and result are confirmed at the end.', steps:['Question','Retrieve','Stream answer','Final citations'], takeaway:'Streaming improves delivery speed without removing validation or evidence.' },
  '05-secure-test-deploy-production-fastapi': { title:'Opening a new bank branch requires more than a door', scenario:'The branch needs identity checks, transaction limits, rehearsed procedures, monitoring and a reliable building before serving customers.', steps:['Secure','Limit','Test','Deploy'], takeaway:'A reachable API is not automatically production-ready.' },
  '01-what-does-a-forward-deployed-engineer-do': { title:'A field engineer solves the actual factory problem', scenario:'The engineer visits the floor, watches the real process, adapts the product and proves that delay or rework has reduced.', steps:['Observe','Frame','Build','Measure'], takeaway:'An FDE owns the path from customer reality to a measurable production outcome.' },
  '02-problem-discovery-and-workflow-mapping': { title:'Map the hospital token journey before digitising it', scenario:'Before building an app, observe registration, waiting, doctor assignment, exceptions and who decides priority.', steps:['Watch','Map','Find constraint','Define outcome'], takeaway:'The stated request is only the start; the real workflow reveals the problem.' },
  '03-design-thin-production-slice': { title:'Pilot one college department before the full campus', scenario:'Use one real class, real attendance data and real mentor approval to prove the end-to-end path before expanding.', steps:['One user','Real data','Safe action','Measure'], takeaway:'A thin slice reduces scope while keeping production reality.' },
  '04-deploy-observe-and-improve': { title:'A bus may run on time but still serve the wrong route', scenario:'Operations data can look healthy while passengers remain dissatisfied. Both system evidence and user outcome must be checked.', steps:['System','Quality','Workflow','Outcome'], takeaway:'Technical health is necessary, but customer value decides success.' },
  '05-turn-field-learning-into-product': { title:'Repeated tailoring becomes a reusable size pattern', scenario:'A tailor notices the same alteration across many customers, creates a standard pattern and keeps only measurements configurable.', steps:['Notice repeat','Extract pattern','Build option','Hand off'], takeaway:'Repeated field evidence can become reusable product capability.' },
  '01-what-is-langchain-build-llm-applications': { title:'A wedding coordinator connects specialised services', scenario:'The coordinator does not cook, decorate or drive; they connect the right providers, instructions and sequence into one reliable event workflow.', steps:['Model','Prompt','Tools','Workflow'], takeaway:'LangChain coordinates model and application components; it is not the model itself.' },
  '02-connect-python-with-llms-using-langchain': { title:'A translator needs a clear brief and output form', scenario:'A translator receives the audience, source text and required format—not only “translate this”—then returns a result the next team can use.', steps:['Configure','Message','Model','Validate'], takeaway:'Good model integration includes context, roles and a predictable output contract.' },
  '03-build-rag-applications-with-your-documents': { title:'A librarian finds the right page before answering', scenario:'Instead of recalling every book, the librarian searches the catalogue, opens relevant pages and answers from visible evidence.', steps:['Load','Index','Retrieve','Ground answer'], takeaway:'RAG retrieves relevant evidence before the model generates an answer.' },
  '04-build-ai-agents-with-tools-and-memory': { title:'A personal assistant uses a diary and approved services', scenario:'The assistant remembers the current request, checks the diary and calls only authorised services while important actions wait for confirmation.', steps:['Goal','Memory','Tool','Check'], takeaway:'An agent combines state and tools inside application-controlled boundaries.' },
  '05-production-ready-langchain-application': { title:'A stage rehearsal is not the public performance', scenario:'A successful rehearsal still needs entry control, backup plans, monitoring and named operators before the auditorium opens.', steps:['Contract','Trace','Protect','Operate'], takeaway:'Production readiness surrounds the chain with evidence and recovery controls.' },
  '01-what-is-rag-give-ai-access-to-your-knowledge': { title:'An advocate checks the correct case file', scenario:'A useful answer comes after finding the authorised, current document—not from confidently recalling a similar case.', steps:['Question','Find file','Read evidence','Answer'], takeaway:'RAG grounds generation in retrieved private or current knowledge.' },
  '02-prepare-documents-loading-cleaning-chunking': { title:'A textbook is organised into teachable lessons', scenario:'A teacher removes duplicate pages, groups related ideas, gives every section a clear label and preserves where it came from.', steps:['Load','Clean','Chunk','Label'], takeaway:'Retrieval quality begins with clean, meaningful and traceable content units.' },
  '03-embeddings-vector-databases-semantic-search': { title:'A bookshop understands meaning beyond exact words', scenario:'A learner asking for “job interview confidence” can be guided to communication books even when the title does not contain the exact phrase.', steps:['Meaning','Vector','Similar items','Rerank'], takeaway:'Semantic search finds related meaning, then filters improve precision.' },
  '04-build-complete-rag-application-python-langchain': { title:'A complete library enquiry desk', scenario:'The desk maintains a catalogue, confirms membership access, finds the best pages, prepares an answer and names every source used.', steps:['Index','Authorise','Retrieve','Cite'], takeaway:'A complete RAG app owns the full evidence path, not only the model call.' },
  '05-production-rag-evaluation-security-deployment': { title:'A trusted library audits both search and answers', scenario:'The library measures whether the correct book was found, whether the reply matches the page and whether restricted material stayed protected.', steps:['Evaluate','Protect','Observe','Improve'], takeaway:'Production RAG quality must be measured at retrieval, answer and access layers.' },
  '01-github-copilot-for-developers': { title:'A skilled pair programmer supports different tasks', scenario:'A teammate may complete a line, explain unfamiliar code, review a plan or implement a bounded task—but the developer still owns the decision.', steps:['Complete','Ask','Plan','Agent'], takeaway:'Choose the smallest Copilot mode that safely fits the job.' },
  '02-give-github-copilot-better-context': { title:'A new teammate needs the project brief', scenario:'“Build the page” is weak. Share the goal, relevant files, brand rules and acceptance checks just as you would with a developer joining the team.', steps:['Goal','Files','Rules','Done'], takeaway:'Context quality determines whether AI output fits the real repository.' },
  '03-debug-test-refactor-with-github-copilot': { title:'A mechanic diagnoses before replacing parts', scenario:'The mechanic reproduces the sound, inspects evidence, changes one likely cause and road-tests the vehicle.', steps:['Reproduce','Inspect','Fix small','Test'], takeaway:'Use Copilot to reason from evidence, not to generate random rewrites.' },
  '04-build-feature-with-github-copilot': { title:'Construct one room before the entire building', scenario:'The team agrees on the plan, completes one usable room, checks safety and then continues—rather than generating the whole building at once.', steps:['Understand','Plan','Build slice','Review'], takeaway:'Small verified changes are easier to trust than one large generated change.' },
  '05-use-github-copilot-responsibly': { title:'An apprentice’s work passes senior review', scenario:'The apprentice can work quickly, but tests, security checks and a named engineer decide what reaches customers.', steps:['Inspect','Test','Secure','Approve'], takeaway:'AI can assist delivery; accountable humans control release.' },
  '01-modern-java-foundations-ai-era': { title:'A house needs a strong plan even with power tools', scenario:'Modern tools accelerate construction, but room purpose, measurements and safety still come from a clear design.', steps:['Requirement','Types','Behaviour','Test'], takeaway:'AI can generate Java; developers still own the domain model and proof.' },
  '02-build-rest-apis-java-spring-boot': { title:'A government service counter has clear responsibilities', scenario:'The counter receives the form, a department applies the rule and the citizen receives a standard receipt or a useful correction message.', steps:['Request','Controller','Service','Response'], takeaway:'Spring layers separate web handling from business decisions.' },
  '03-connect-spring-boot-database': { title:'A registrar protects one complete admission transaction', scenario:'Student, course and payment records must change together; a partial update would leave the admission incorrect.', steps:['Service','Repository','Entity','Database'], takeaway:'Persistence maps domain data and transactions protect complete business work.' },
  '04-add-generative-ai-rag-java': { title:'An HR officer checks policy before replying', scenario:'The officer finds the current leave policy, selects the relevant paragraph and responds with the section reference.', steps:['Question','Retrieve','Ground','Cite'], takeaway:'A Java AI assistant should answer from authorised evidence, not model memory alone.' },
  '05-build-deploy-enterprise-ai-application': { title:'A factory machine needs guards, tests and monitoring', scenario:'A working prototype enters production only after access control, test runs, operating indicators and recovery steps are ready.', steps:['Secure','Test','Observe','Deploy'], takeaway:'Enterprise delivery is proven by controls and operational evidence.' },
  '01-sql-foundations-ask-questions-using-data': { title:'Ask the shop ledger one precise question', scenario:'Instead of reading every sale, request only Chennai orders above ₹1,000, sort the newest first and view ten results.', steps:['Choose columns','Filter rows','Sort','Limit'], takeaway:'SQL converts a business question into a precise request for rows and columns.' },
  '02-analyse-business-data-with-sql': { title:'A tuition centre groups fees by course', scenario:'Individual payment rows become useful when grouped into course totals, monthly counts and unpaid balances.', steps:['Rows','Calculate','Group','Explain'], takeaway:'Aggregation turns transactions into decision-ready measures.' },
  '03-connect-data-across-tables-joins': { title:'Match student roll numbers across registers', scenario:'Attendance, fees and course details live in separate registers; the roll number connects the correct records without mixing students.', steps:['Primary key','Foreign key','Join','Verify'], takeaway:'Joins create meaning by following reliable relationships between tables.' },
  '04-sql-data-rag-ai-agent-workflows': { title:'A manager asks a question; controls approve the query', scenario:'“Which courses grew this month?” becomes proposed SQL, but read-only rules, allowed tables and result limits decide whether it runs.', steps:['Question','Generate SQL','Validate','Explain result'], takeaway:'The model proposes; deterministic controls authorise and bound execution.' },
  '05-write-production-ready-sql': { title:'A busy railway counter needs safe, fast transactions', scenario:'The correct passenger record must be found quickly, values must be handled safely and a failed payment must not leave half a booking.', steps:['Parameterise','Index','Transact','Audit'], takeaway:'Production SQL combines correctness, security, speed and recoverability.' },
};

export function BeginnerAnalogy({ slug }: { slug: string }) {
  const analogy = analogies[slug];
  if (!analogy) return null;
  return <section className="beginner-analogy" aria-label="Beginner-friendly analogy">
    <header><span><MapPin/></span><div><small>FAMILIAR SCENARIO</small><h2>{analogy.title}</h2></div></header>
    <p>{analogy.scenario}</p>
    <div className="beginner-analogy-flow">{analogy.steps.map((step,index)=><div className="beginner-analogy-wrap" key={step}><span><b>0{index+1}</b><strong>{step}</strong></span>{index<3&&<ArrowRight/>}</div>)}</div>
    <footer><Lightbulb/><p><b>Connect the idea:</b> {analogy.takeaway}</p></footer>
  </section>;
}
